"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input, Label } from "@/components/ui/form";
import { Separator } from "@/components/ui/separator";
export default function SignInPage() { const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setMessage(""); try { const response = await fetch("/api/v1/signin-flow", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || "Sign-in is unavailable."); router.push(payload.data.redirect); } catch (error) { setMessage(error instanceof Error ? error.message : "Sign-in is unavailable."); setLoading(false); } }; return <main className="auth-new"><Card><CardHeader><p className="auth-brand">MSME Arogya360</p><CardTitle>Welcome back</CardTitle><CardDescription>Sign in to your secure MSME credit-intelligence workspace.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="auth-form-new"><div><Label htmlFor="email">Work email</Label><Input id="email" value={email} onChange={(event) => setEmail(event.target.value)} type="email" placeholder="name@organisation.com" required /></div><div><Label htmlFor="password">Password</Label><div className="password-input"><Input id="password" value={password} onChange={(event) => setPassword(event.target.value)} type={showPassword ? "text" : "password"} placeholder="Minimum 8 characters" minLength={8} required /><Button type="button" variant="ghost" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? "Hide" : "Show"}</Button></div></div>{message && <Alert className="error-alert"><AlertTitle>Sign-in unavailable</AlertTitle><AlertDescription>{message}</AlertDescription></Alert>}<Button type="submit" disabled={loading}>{loading ? "Signing in…" : "Sign in to demo"}</Button></form><Separator /><p className="auth-note">Synthetic demo session only. No production credentials are used.</p><div className="auth-links"><Link href="/forgot-password">Forgot password?</Link><Link href="/signup">Create an account</Link></div></CardContent></Card></main>; }
