import Link from "next/link";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { PageHeader } from "@/components/foundation/page-header";
import { TrackCard } from "@/components/foundation/track-card";
export default function AppHome() { return <div className="app-overview"><PageHeader eyebrow="IDBI Innovate 2026" title="Welcome to MSME Arogya360" description="A banking-grade workspace for structured MSME onboarding, evidence readiness, and future credit-intelligence modules." action={<Link href="/app/onboarding"><Button>Open onboarding</Button></Link>} /><Alert><AlertTitle>Prototype environment</AlertTitle><AlertDescription>Business Profile onboarding uses synthetic evidence. Financial Health and Default Risk remain upcoming modules; no score, prediction, sanction, or rejection is produced here.</AlertDescription></Alert><section className="dashboard-grid"><Card className="welcome-card"><CardHeader><Badge variant="success">Onboarding foundation available</Badge><CardTitle>Evidence readiness, made reviewable</CardTitle></CardHeader><CardContent><p>Start with business profile and KYB context, then review structured evidence and incomplete items.</p><Progress value={72} label="Demo onboarding readiness" /><small>Demo readiness placeholder: 72%</small></CardContent></Card><TrackCard label="Track 03" title="Financial Health Card" description="Current financial health and credit-readiness context from permitted alternate data." status="Upcoming" /><TrackCard label="Track 04" title="Default Risk Intelligence" description="Explainable future stress context for assisted risk review." status="Upcoming" /></section><section className="two-grid"><Card><CardHeader><CardTitle>Data readiness</CardTitle></CardHeader><CardContent><p>Structured onboarding evidence is available in the synthetic demo. Connector and sandbox adapters will be introduced later.</p><Separator /><Badge variant="warning">Evidence review required</Badge></CardContent></Card><Card><CardHeader><CardTitle>Recent activity</CardTitle></CardHeader><CardContent><p>No production activity is shown in this demo workspace.</p><Separator /><Link href="/app/onboarding"><Button variant="outline">Review onboarding status</Button></Link></CardContent></Card><Card><CardHeader><CardTitle>Next steps</CardTitle></CardHeader><CardContent><p>Complete structured onboarding evidence before Track 03 Financial Health Card implementation.</p><Link href="/app/onboarding"><Button>Continue onboarding</Button></Link></CardContent></Card></section></div>; }
