import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/application-progress/route.ts";
import { PATCH } from "../app/api/v1/application-progress/[id]/route.ts";
import { applicationProgressAuditCount } from "../lib/application-progress.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded synthetic application progress with trace id", async () => { const response = await GET(new Request("http://test/api/v1/application-progress", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data[0].completion, 72); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete application progress creation", async () => { const response = await POST(new Request("http://test/api/v1/application-progress", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized application progress access", async () => { const response = await GET(new Request("http://test/api/v1/application-progress", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits application progress changes", async () => { const before = applicationProgressAuditCount(); const response = await PATCH(new Request("http://test/api/v1/application-progress/progress_demo_001", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ current_stage: "Assisted review" }) }), { params: Promise.resolve({ id: "progress_demo_001" }) }); assert.equal(response.status, 200); assert.equal(applicationProgressAuditCount(), before + 1); });
