import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/business-profile/route.ts";
import { PATCH } from "../app/api/v1/business-profile/[id]/route.ts";
import { businessProfileAuditCount } from "../lib/business-profile.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded synthetic business profile with trace id", async () => { const response = await GET(new Request("http://test/api/v1/business-profile", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data[0].trade_name, "Saraswati Precision Works"); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete business profile creation", async () => { const response = await POST(new Request("http://test/api/v1/business-profile", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized business profile access", async () => { const response = await GET(new Request("http://test/api/v1/business-profile", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits business profile changes", async () => { const before = businessProfileAuditCount(); const response = await PATCH(new Request("http://test/api/v1/business-profile/business_demo_saraswati", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ industry: "Precision manufacturing" }) }), { params: Promise.resolve({ id: "business_demo_saraswati" }) }); assert.equal(response.status, 200); assert.equal(businessProfileAuditCount(), before + 1); });
