import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/documents-upload/route.ts";
import { PATCH } from "../app/api/v1/documents-upload/[id]/route.ts";
import { documentsUploadAuditCount } from "../lib/documents-upload.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded synthetic document metadata with trace id", async () => { const response = await GET(new Request("http://test/api/v1/documents-upload", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data[1].upload_status, "Missing"); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete document metadata creation", async () => { const response = await POST(new Request("http://test/api/v1/documents-upload", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized document upload access", async () => { const response = await GET(new Request("http://test/api/v1/documents-upload", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits document upload changes", async () => { const before = documentsUploadAuditCount(); const response = await PATCH(new Request("http://test/api/v1/documents-upload/document_demo_bank_001", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ consent_status: "Recorded" }) }), { params: Promise.resolve({ id: "document_demo_bank_001" }) }); assert.equal(response.status, 200); assert.equal(documentsUploadAuditCount(), before + 1); });
