import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/north-star-metrics/route.ts";
import { PATCH } from "../app/api/v1/north-star-metrics/[id]/route.ts";
import { metricAuditEventCount } from "../lib/north-star-metrics.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded metrics to an authorized analyst", async () => { const response = await GET(new Request("http://test/api/v1/north-star-metrics", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data[0].name, "Evidence-ready MSME journeys"); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete metric payloads", async () => { const response = await POST(new Request("http://test/api/v1/north-star-metrics", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized metric access", async () => { const response = await GET(new Request("http://test/api/v1/north-star-metrics", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits metric updates", async () => { const before = metricAuditEventCount(); const response = await PATCH(new Request("http://test/api/v1/north-star-metrics/metric_onboard_001", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ status: "On track" }) }), { params: Promise.resolve({ id: "metric_onboard_001" }) }); assert.equal(response.status, 200); assert.equal(metricAuditEventCount(), before + 1); });
