import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/ntb-ntc-identification/route.ts";
import { PATCH } from "../app/api/v1/ntb-ntc-identification/[id]/route.ts";
import { ntbNtcIdentificationAuditCount } from "../lib/ntb-ntc-identification.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded synthetic NTB/NTC identification with trace id", async () => { const response = await GET(new Request("http://test/api/v1/ntb-ntc-identification", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data[0].segment, "New to Bank (NTB)"); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete NTB/NTC identification creation", async () => { const response = await POST(new Request("http://test/api/v1/ntb-ntc-identification", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized NTB/NTC identification access", async () => { const response = await GET(new Request("http://test/api/v1/ntb-ntc-identification", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits NTB/NTC identification changes", async () => { const before = ntbNtcIdentificationAuditCount(); const response = await PATCH(new Request("http://test/api/v1/ntb-ntc-identification/ntb_ntc_demo_001", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ status: "Ready for review" }) }), { params: Promise.resolve({ id: "ntb_ntc_demo_001" }) }); assert.equal(response.status, 200); assert.equal(ntbNtcIdentificationAuditCount(), before + 1); });
