import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/pan-gstin-verification/route.ts";
import { PATCH } from "../app/api/v1/pan-gstin-verification/[id]/route.ts";
import { panGstinVerificationAuditCount } from "../lib/pan-gstin-verification.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded synthetic PAN and GSTIN verifications", async () => { const response = await GET(new Request("http://test/api/v1/pan-gstin-verification", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data.length, 2); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete PAN/GSTIN verification creation", async () => { const response = await POST(new Request("http://test/api/v1/pan-gstin-verification", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized PAN/GSTIN verification access", async () => { const response = await GET(new Request("http://test/api/v1/pan-gstin-verification", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits PAN/GSTIN verification changes", async () => { const before = panGstinVerificationAuditCount(); const response = await PATCH(new Request("http://test/api/v1/pan-gstin-verification/gstin_demo_001", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ consent_status: "Recorded" }) }), { params: Promise.resolve({ id: "gstin_demo_001" }) }); assert.equal(response.status, 200); assert.equal(panGstinVerificationAuditCount(), before + 1); });
