import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/udyam-verification/route.ts";
import { PATCH } from "../app/api/v1/udyam-verification/[id]/route.ts";
import { udyamVerificationAuditCount } from "../lib/udyam-verification.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded synthetic Udyam verification with trace id", async () => { const response = await GET(new Request("http://test/api/v1/udyam-verification", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data[0].verification_status, "Verified"); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete Udyam verification creation", async () => { const response = await POST(new Request("http://test/api/v1/udyam-verification", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized Udyam verification access", async () => { const response = await GET(new Request("http://test/api/v1/udyam-verification", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits Udyam verification changes", async () => { const before = udyamVerificationAuditCount(); const response = await PATCH(new Request("http://test/api/v1/udyam-verification/udyam_demo_001", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ consent_status: "Recorded" }) }), { params: Promise.resolve({ id: "udyam_demo_001" }) }); assert.equal(response.status, 200); assert.equal(udyamVerificationAuditCount(), before + 1); });
