import assert from "node:assert/strict";
import test from "node:test";
import { GET, POST } from "../app/api/v1/user-role-map/route.ts";
import { PATCH } from "../app/api/v1/user-role-map/[id]/route.ts";
import { roleAuditEventCount } from "../lib/user-role-map.ts";
const headers = { "x-user-role": "bank_analyst" };
test("returns seeded role mapping to an authorized analyst", async () => { const response = await GET(new Request("http://test/api/v1/user-role-map", { headers })); const payload = await response.json(); assert.equal(response.status, 200); assert.equal(payload.data[0].role, "Borrower"); assert.ok(payload.trace_id.startsWith("trc_")); });
test("rejects incomplete role mapping payloads", async () => { const response = await POST(new Request("http://test/api/v1/user-role-map", { method: "POST", headers: { ...headers, "content-type": "application/json" }, body: "{}" })); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.error.code, "VALIDATION_ERROR"); });
test("denies unauthorized role-map access", async () => { const response = await GET(new Request("http://test/api/v1/user-role-map", { headers: { "x-user-role": "borrower" } })); const payload = await response.json(); assert.equal(response.status, 403); assert.equal(payload.error.code, "AUTHORIZATION_DENIED"); assert.equal("data" in payload, false); });
test("audits role-map updates", async () => { const before = roleAuditEventCount(); const response = await PATCH(new Request("http://test/api/v1/user-role-map/role_borrower_001", { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ status: "Active" }) }), { params: Promise.resolve({ id: "role_borrower_001" }) }); assert.equal(response.status, 200); assert.equal(roleAuditEventCount(), before + 1); });
