"use client";
import { useEffect, useState } from "react";
type Consent = { id: string; purpose: string; data_range: string; status: "Awaiting approval" | "Approved" | "Consumed" | "Revoked"; expires_at: string; consent_handle: string; freshness: string; completeness: number; explanation: string; snapshot_id?: string };
const headers = { "x-user-role": "bank_analyst" };
export default function AaOneTimeConsentPanel() {
  const [consents, setConsents] = useState<Consent[]>([]); const [state, setState] = useState<"loading" | "ready" | "error" | "unauthorized">("loading"); const [message, setMessage] = useState(""); const [retry, setRetry] = useState(0); const [busy, setBusy] = useState("");
  useEffect(() => { let active = true; void fetch("/api/v1/aa-one-time-consent", { headers }).then(async (response) => { const result = await response.json(); if (!active) return; if (response.status === 403) return setState("unauthorized"); if (!response.ok) throw new Error(result.error?.message); setConsents(result.data.consents); setState("ready"); }).catch((error: unknown) => { if (active) { setState("error"); setMessage(error instanceof Error ? error.message : "We couldn’t load Account Aggregator consent."); } }); return () => { active = false; }; }, [retry]);
  async function update(id: string, status: Consent["status"]) { setBusy(id); try { const response = await fetch(`/api/v1/aa-one-time-consent/${id}`, { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ status }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message); setConsents((items) => items.map((item) => item.id === id ? result.data : item)); } catch (error) { setMessage(error instanceof Error ? error.message : "We couldn’t update Account Aggregator consent."); } finally { setBusy(""); } }
  if (state === "loading") return <section className="detail-card aa-panel"><strong>Checking one-time Account Aggregator consent…</strong></section>;
  if (state === "unauthorized") return <section className="detail-card aa-panel"><strong>Account Aggregator consent unavailable</strong><span>Your role cannot view this consent evidence.</span></section>;
  if (state === "error") return <section className="detail-card aa-panel"><strong>Account Aggregator consent unavailable</strong><span>{message}</span><button className="ui-button ui-button-outline" onClick={() => { setState("loading"); setRetry((value) => value + 1); }}>Try again</button></section>;
  return <section className="detail-card aa-panel"><div className="detail-top"><div><p className="eyebrow">Account Aggregator</p><h2>One-time data permission</h2></div><span className="status ready">One-time only</span></div>{message && <p className="address-missing">{message}</p>}{consents.length ? consents.map((consent) => <div className="recommendation" key={consent.id}><span>{consent.consent_handle} · expires {new Date(consent.expires_at).toLocaleDateString("en-IN")}</span><strong>{consent.purpose}</strong><p>{consent.explanation}</p><small>{consent.data_range} · {consent.completeness}% complete · {consent.freshness} evidence{consent.snapshot_id ? ` · immutable snapshot ${consent.snapshot_id}` : ""}</small><div className="button-row">{consent.status === "Awaiting approval" && <button className="ui-button" disabled={busy === consent.id} onClick={() => update(consent.id, "Approved")}>Approve one-time consent</button>}{consent.status === "Approved" && <button className="ui-button" disabled={busy === consent.id} onClick={() => update(consent.id, "Consumed")}>Retrieve summary once</button>}{["Awaiting approval", "Approved"].includes(consent.status) && <button className="ui-button ui-button-outline" disabled={busy === consent.id} onClick={() => update(consent.id, "Revoked")}>Cancel</button>}<span className={`status ${consent.status === "Consumed" ? "ready" : consent.status === "Revoked" ? "review" : ""}`}>{consent.status}</span></div></div>) : <div className="empty-state"><strong>No one-time Account Aggregator consent</strong><span>No account summary has been requested in the synthetic demo.</span></div>}<p className="redaction-note">One-time consent limits access to the stated purpose and period. Only a structured summary is retained; raw account payloads are excluded.</p></section>;
}
