"use client";
import { useEffect, useState } from "react";
type Consent = { id: string; purpose: string; frequency: string; status: "Active" | "Paused" | "Expiring soon" | "Revoked"; expires_at: string; consent_handle: string; freshness: string; completeness: number; explanation: string; next_sync_at?: string };
const headers = { "x-user-role": "bank_analyst" };
export default function AaPeriodicMonitoringConsentPanel() {
  const [consents, setConsents] = useState<Consent[]>([]); const [state, setState] = useState<"loading" | "ready" | "error" | "unauthorized">("loading"); const [message, setMessage] = useState(""); const [retry, setRetry] = useState(0); const [busy, setBusy] = useState("");
  useEffect(() => { let active = true; void fetch("/api/v1/aa-periodic-monitoring-consent", { headers }).then(async (response) => { const result = await response.json(); if (!active) return; if (response.status === 403) return setState("unauthorized"); if (!response.ok) throw new Error(result.error?.message); setConsents(result.data.consents); setState("ready"); }).catch((error: unknown) => { if (active) { setState("error"); setMessage(error instanceof Error ? error.message : "We couldn’t load periodic monitoring consent."); } }); return () => { active = false; }; }, [retry]);
  async function update(id: string, status: Consent["status"]) { setBusy(id); try { const response = await fetch(`/api/v1/aa-periodic-monitoring-consent/${id}`, { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ status }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message); setConsents((items) => items.map((item) => item.id === id ? result.data : item)); } catch (error) { setMessage(error instanceof Error ? error.message : "We couldn’t update periodic monitoring consent."); } finally { setBusy(""); } }
  if (state === "loading") return <section className="detail-card aa-panel"><strong>Checking periodic Account Aggregator consent…</strong></section>;
  if (state === "unauthorized") return <section className="detail-card aa-panel"><strong>Periodic monitoring consent unavailable</strong><span>Your role cannot view this consent evidence.</span></section>;
  if (state === "error") return <section className="detail-card aa-panel"><strong>Periodic monitoring consent unavailable</strong><span>{message}</span><button className="ui-button ui-button-outline" onClick={() => { setState("loading"); setRetry((value) => value + 1); }}>Try again</button></section>;
  return <section className="detail-card aa-panel"><div className="detail-top"><div><p className="eyebrow">Account Aggregator</p><h2>Periodic monitoring permission</h2></div><span className="status ready">Scheduled access</span></div>{message && <p className="address-missing">{message}</p>}{consents.length ? consents.map((consent) => <div className="recommendation" key={consent.id}><span>{consent.consent_handle} · expires {new Date(consent.expires_at).toLocaleDateString("en-IN")}</span><strong>{consent.purpose}</strong><p>{consent.explanation}</p><small>{consent.frequency} · {consent.completeness}% complete · {consent.freshness} evidence{consent.next_sync_at ? ` · next sync ${new Date(consent.next_sync_at).toLocaleDateString("en-IN")}` : ""}</small><div className="button-row">{consent.status === "Active" && <button className="ui-button ui-button-outline" disabled={busy === consent.id} onClick={() => update(consent.id, "Paused")}>Pause monitoring</button>}{consent.status === "Paused" && <button className="ui-button" disabled={busy === consent.id} onClick={() => update(consent.id, "Active")}>Resume monitoring</button>}{!["Revoked"].includes(consent.status) && <button className="ui-button ui-button-outline" disabled={busy === consent.id} onClick={() => update(consent.id, "Revoked")}>Withdraw consent</button>}<span className={`status ${consent.status === "Active" ? "ready" : "review"}`}>{consent.status}</span></div></div>) : <div className="empty-state"><strong>No periodic monitoring consent</strong><span>No scheduled account summaries are configured in the synthetic demo.</span></div>}<p className="redaction-note">Periodic consent is purpose- and frequency-limited. It retains structured, immutable summaries only; raw account payloads are excluded.</p></section>;
}
