"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Identification = { id: string; application_id: string; segment: string; status: string; confidence: number; freshness: string; completeness: number; explanation: string; evidence: string[]; missing_data: string[]; snapshot_id: string };
const headers = { "x-user-role": "bank_analyst" };
export default function NtbNtcIdentificationWorkspace({ applicationId }: { applicationId?: string }) {
  const [items, setItems] = useState<Identification[]>([]); const [state, setState] = useState<"loading" | "ready" | "error" | "unauthorized">("loading"); const [message, setMessage] = useState(""); const [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; void fetch("/api/v1/ntb-ntc-identification", { headers }).then(async (response) => { const result = await response.json(); if (!active) return; if (response.status === 403) return setState("unauthorized"); if (!response.ok) throw new Error(result.error?.message); setItems(applicationId ? result.data.filter((item: Identification) => item.application_id === applicationId) : result.data); setState("ready"); }).catch((error: unknown) => { if (active) { setState("error"); setMessage(error instanceof Error ? error.message : "We couldn’t load NTB/NTC identification."); } }); return () => { active = false; }; }, [applicationId, retry]);
  if (state === "loading") return <main className="state-panel"><span className="spinner" aria-label="Loading" /><strong>Loading onboarding segment…</strong></main>;
  if (state === "unauthorized") return <main className="state-panel error-state"><strong>Access unavailable</strong><span>You do not have permission to view NTB/NTC identification.</span></main>;
  if (state === "error") return <main className="state-panel error-state"><strong>Onboarding segment unavailable</strong><span>{message}</span><button onClick={() => { setState("loading"); setMessage(""); setRetry((value) => value + 1); }}>Try again</button></main>;
  if (!items.length) return <main className="workspace"><section className="empty-state"><strong>No onboarding segment found</strong><span>This application has no NTB/NTC identification in the synthetic demo data.</span><Link className="landing-cta small" href="/app/onboarding">Return to onboarding</Link></section></main>;
  const item = items[0];
  return <main className="workspace"><nav className="workspace-nav" aria-label="NTB NTC identification navigation"><Link href="/app/onboarding">Business profile</Link><Link href="/app/onboarding/documents">Documents</Link><Link href="/app/onboarding/progress">Application progress</Link><Link className="active" href="/app/onboarding/ntb-ntc">NTB / NTC</Link>{applicationId && <Link href={`/app/applications/${applicationId}?section=ntb-ntc`}>Application</Link>}</nav><section className="hero"><div><p className="eyebrow">MSME Arogya360 / onboarding context</p><h1>NTB / NTC identification</h1><p>Understand onboarding context from permitted synthetic evidence. This is a review aid only—not a bureau finding, risk score, or credit decision.</p></div><div className="hero-status"><span className="live-dot" />{item.status}<small>{item.confidence}% confidence</small></div></section>{item.missing_data.length > 0 && <section className="info-banner business-alert"><strong>Review context is still improving.</strong> {item.missing_data.join(" and ")} will increase evidence completeness; the available segment can still be reviewed.</section>}<section className="metrics" aria-label="NTB and NTC identification summary"><article className="metric"><span>Onboarding segment</span><strong>{item.segment}</strong><small>Not a lending or risk decision</small></article><article className="metric"><span>Confidence</span><strong>{item.confidence}%</strong><small>{item.completeness}% evidence complete</small></article><article className="metric"><span>Evidence freshness</span><strong>{item.freshness}</strong><small>Snapshot retained for review</small></article></section><section className="content-grid"><article className="queue-card"><div className="section-heading"><div><p className="eyebrow">Evidence used</p><h2>Explainable segment context</h2></div></div><ul className="evidence-points">{item.evidence.map((evidence) => <li key={evidence}>{evidence}</li>)}</ul>{item.missing_data.length > 0 && <div className="missing-evidence"><strong>Evidence still needed</strong><ul>{item.missing_data.map((entry) => <li key={entry}>{entry}</li>)}</ul></div>}</article><article className="detail-card"><div className="detail-top"><div><p className="eyebrow">Review guidance</p><h2>Purpose-limited classification</h2></div><span className={`status ${item.status === "Ready for review" ? "ready" : "review"}`}>{item.status}</span></div><div className="recommendation"><span>Why this segment was suggested</span><strong>{item.segment}</strong><p>{item.explanation}</p></div><div className="progress-meter" aria-label={`${item.confidence}% confidence`}><span>Confidence</span><strong>{item.confidence}%</strong><div><i style={{ width: `${item.confidence}%` }} /></div></div><p className="redaction-note">Snapshot: {item.snapshot_id}. The classification is immutable review context and does not reveal model internals.</p></article></section></main>;
}
