"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Verification = { id: string; application_id: string; verification_type: string; masked_reference: string; verification_status: string; consent_status: string; source_id: string; source_observed_at: string; freshness: string; completeness: number; explanation: string; missing_data: string[] };
const headers = { "x-user-role": "bank_analyst" };
export default function PanGstinVerificationWorkspace({ applicationId }: { applicationId?: string }) {
  const [items, setItems] = useState<Verification[]>([]); const [state, setState] = useState<"loading" | "ready" | "error" | "unauthorized">("loading"); const [message, setMessage] = useState(""); const [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; void fetch("/api/v1/pan-gstin-verification", { headers }).then(async (response) => { const result = await response.json(); if (!active) return; if (response.status === 403) return setState("unauthorized"); if (!response.ok) throw new Error(result.error?.message); setItems(applicationId ? result.data.filter((item: Verification) => item.application_id === applicationId) : result.data); setState("ready"); }).catch((error: unknown) => { if (active) { setState("error"); setMessage(error instanceof Error ? error.message : "We couldn’t load PAN/GSTIN verification."); } }); return () => { active = false; }; }, [applicationId, retry]);
  if (state === "loading") return <main className="state-panel"><span className="spinner" aria-label="Loading" /><strong>Loading PAN/GSTIN verification…</strong></main>;
  if (state === "unauthorized") return <main className="state-panel error-state"><strong>Access unavailable</strong><span>You do not have permission to view PAN/GSTIN verification.</span></main>;
  if (state === "error") return <main className="state-panel error-state"><strong>PAN/GSTIN verification unavailable</strong><span>{message}</span><button onClick={() => { setState("loading"); setMessage(""); setRetry((value) => value + 1); }}>Try again</button></main>;
  if (!items.length) return <main className="workspace"><section className="empty-state"><strong>No PAN/GSTIN record found</strong><span>This application has no tax-identity verification in the synthetic demo data.</span><Link className="landing-cta small" href="/app/onboarding">Return to onboarding</Link></section></main>;
  const stale = items.filter((item) => item.freshness === "Stale"); const pending = items.filter((item) => item.missing_data.length);
  return <main className="workspace"><nav className="workspace-nav" aria-label="Tax identity verification navigation"><Link href="/app/onboarding">Business profile</Link><Link href="/app/onboarding/promoters">Promoters</Link><Link href="/app/onboarding/udyam">Udyam verification</Link><Link className="active" href="/app/onboarding/pan-gstin">PAN/GSTIN</Link>{applicationId && <Link href={`/app/applications/${applicationId}`}>Application</Link>}</nav><section className="hero"><div><p className="eyebrow">MSME Arogya360 / KYB onboarding</p><h1>PAN and GSTIN verification</h1><p>Review masked tax-identity evidence for an assisted onboarding decision. This prototype uses synthetic data only.</p></div><div className="hero-status"><span className="live-dot" />{items.filter((item) => item.verification_status === "Verified").length} verified<small>{items.length} verification records</small></div></section>{(stale.length || pending.length) && <section className="info-banner business-alert"><strong>Review before relying on this record.</strong> {stale.length ? `${stale.length} source is stale.` : ""} {pending.length ? `${pending.length} verification has missing evidence.` : ""}</section>}<section className="metrics" aria-label="PAN and GSTIN verification summary"><article className="metric"><span>Verified records</span><strong>{items.filter((item) => item.verification_status === "Verified").length} of {items.length}</strong><small>Tax identity relationship checks</small></article><article className="metric"><span>Consent evidence</span><strong>{items.filter((item) => item.consent_status === "Recorded").length} recorded</strong><small>Purpose-limited verification access</small></article><article className="metric"><span>Freshness</span><strong>{stale.length ? "Review required" : "Current"}</strong><small>{stale.length ? "Stale tax evidence present" : "All source evidence is current"}</small></article></section><section className="tax-verification-grid">{items.map((item) => <article className="detail-card tax-card" key={item.id}><div className="detail-top"><div><p className="eyebrow">{item.verification_type} record</p><h2>{item.masked_reference}</h2></div><span className={`status ${item.verification_status === "Verified" ? "ready" : "review"}`}>{item.verification_status}</span></div><div className="recommendation"><span>{item.completeness}% complete · {item.consent_status} consent</span><strong>{item.freshness} evidence</strong><p>{item.explanation}</p></div><div className="promoter-meta"><span>Source: <b>{item.source_id}</b></span><span>Observed: <b>{new Date(item.source_observed_at).toLocaleDateString("en-IN")}</b></span></div>{item.missing_data.length > 0 && <div className="missing-evidence"><strong>Missing data</strong><ul>{item.missing_data.map((entry) => <li key={entry}>{entry}</li>)}</ul></div>}</article>)}</section><p className="redaction-note">Only masked PAN and GSTIN references are shown. Raw identifiers are never returned to this UI.</p></main>;
}
