import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";

export { apiError, getActor, isAllowedRole, traceId };
export type AaConsentStatus = "Awaiting approval" | "Approved" | "Consumed" | "Revoked";
export type AaOneTimeConsent = { id: string; business_name: string; purpose: string; data_range: string; status: AaConsentStatus; expires_at: string; consent_handle: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; snapshot_id?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type SourceSnapshot = { id: string; consent_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; summary: string; immutable: true };

let consents: AaOneTimeConsent[] = [{ id: "aa_consent_demo_001", business_name: "Saraswati Precision Works", purpose: "Financial health cash-flow review", data_range: "Last 90 days", status: "Approved", expires_at: "2026-07-16T23:59:59.000Z", consent_handle: "AA-••••-8192", source_id: "synthetic_aa_consent_2026_07", source_observed_at: "2026-07-13T08:25:00.000Z", freshness: "Current", completeness: 100, explanation: "A one-time permission can retrieve a summary for the chosen period only. It does not create ongoing access.", created_at: "2026-07-13T08:25:00.000Z", updated_at: "2026-07-13T08:25:00.000Z", created_by: "demo.borrower", updated_by: "demo.borrower" }];
const snapshots: SourceSnapshot[] = [];
const auditEvents: Array<Record<string, string>> = [];
export function getAaOneTimeConsents() { return { consents, source_snapshots: snapshots }; }
export function getAaOneTimeConsent(id: string) { return consents.find((consent) => consent.id === id); }
export function createAaOneTimeConsent(input: Pick<AaOneTimeConsent, "business_name" | "purpose" | "data_range">, actor: string) { const now = new Date().toISOString(); const consent: AaOneTimeConsent = { id: `aa_consent_${crypto.randomUUID()}`, ...input, status: "Awaiting approval", expires_at: new Date(Date.now() + 3 * 86400000).toISOString(), consent_handle: "AA-••••-" + Math.floor(1000 + Math.random() * 9000), source_id: "synthetic_aa_consent_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Approval is needed before a purpose-limited, one-time account summary can be requested.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; consents = [consent, ...consents]; writeAudit("aa_one_time_consent.created", consent.id, actor); return consent; }
export function updateAaOneTimeConsent(id: string, status: AaConsentStatus, actor: string) { const current = getAaOneTimeConsent(id); if (!current) return undefined; const now = new Date().toISOString(); let snapshot_id = current.snapshot_id; let completeness = current.completeness; if (status === "Consumed" && !snapshot_id) { const snapshot: SourceSnapshot = { id: `snapshot_aa_${crypto.randomUUID()}`, consent_id: id, source_id: "synthetic_aa_summary_2026_07", observed_at: now, freshness: "Current", completeness: 94, summary: "A structured 90-day cash-flow summary is available for assisted review; raw account payloads are excluded.", immutable: true }; snapshots.unshift(snapshot); snapshot_id = snapshot.id; completeness = snapshot.completeness; } const updated = { ...current, status, snapshot_id, completeness, updated_at: now, updated_by: actor }; consents = consents.map((consent) => consent.id === id ? updated : consent); writeAudit("aa_one_time_consent.updated", id, actor); return updated; }
export function aaOneTimeConsentAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
