import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type PeriodicStatus = "Active" | "Paused" | "Expiring soon" | "Revoked";
export type PeriodicMonitoringConsent = { id: string; business_name: string; purpose: string; frequency: "Monthly" | "Quarterly"; status: PeriodicStatus; starts_at: string; expires_at: string; consent_handle: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; next_sync_at?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type MonitoringSnapshot = { id: string; consent_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; summary: string; immutable: true };
let consents: PeriodicMonitoringConsent[] = [{ id: "aa_periodic_demo_001", business_name: "Saraswati Precision Works", purpose: "Financial health monitoring", frequency: "Monthly", status: "Active", starts_at: "2026-06-13T08:30:00.000Z", expires_at: "2026-12-13T23:59:59.000Z", consent_handle: "AA-••••-4629", source_id: "synthetic_aa_periodic_2026_07", source_observed_at: "2026-07-13T08:30:00.000Z", freshness: "Current", completeness: 94, explanation: "Monthly summaries help identify changes that may need assisted review. You can pause or withdraw this permission at any time.", next_sync_at: "2026-08-13T08:30:00.000Z", created_at: "2026-06-13T08:30:00.000Z", updated_at: "2026-07-13T08:30:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }, { id: "aa_periodic_demo_002", business_name: "Saraswati Precision Works", purpose: "Cash-flow trend monitoring", frequency: "Quarterly", status: "Expiring soon", starts_at: "2026-01-20T10:00:00.000Z", expires_at: "2026-07-20T23:59:59.000Z", consent_handle: "AA-••••-2207", source_id: "synthetic_aa_periodic_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 76, explanation: "Renew this quarterly monitoring permission to continue receiving structured cash-flow summaries.", created_at: "2026-01-20T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }];
const snapshots: MonitoringSnapshot[] = [{ id: "snapshot_periodic_demo_001", consent_id: "aa_periodic_demo_001", source_id: "synthetic_aa_monthly_summary_2026_07", observed_at: "2026-07-13T08:30:00.000Z", freshness: "Current", completeness: 94, summary: "Monthly cash-flow summary is stable. It is a structured immutable input for assisted review, not a credit decision.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getPeriodicMonitoringConsents() { return { consents, source_snapshots: snapshots }; } export function getPeriodicMonitoringConsent(id: string) { return consents.find((consent) => consent.id === id); }
export function createPeriodicMonitoringConsent(input: Pick<PeriodicMonitoringConsent, "business_name" | "purpose" | "frequency">, actor: string) { const now = new Date().toISOString(); const consent: PeriodicMonitoringConsent = { id: `aa_periodic_${crypto.randomUUID()}`, ...input, status: "Active", starts_at: now, expires_at: new Date(Date.now() + 180 * 86400000).toISOString(), consent_handle: "AA-••••-" + Math.floor(1000 + Math.random() * 9000), source_id: "synthetic_aa_periodic_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Periodic permission was recorded for the stated purpose and frequency. The first structured summary will arrive at the next scheduled sync.", next_sync_at: new Date(Date.now() + 30 * 86400000).toISOString(), created_at: now, updated_at: now, created_by: actor, updated_by: actor }; consents = [consent, ...consents]; writeAudit("aa_periodic_monitoring_consent.created", consent.id, actor); return consent; }
export function updatePeriodicMonitoringConsent(id: string, status: PeriodicStatus, actor: string) { const current = getPeriodicMonitoringConsent(id); if (!current) return undefined; const updated = { ...current, status, next_sync_at: status === "Active" ? current.next_sync_at : undefined, updated_at: new Date().toISOString(), updated_by: actor }; consents = consents.map((consent) => consent.id === id ? updated : consent); writeAudit("aa_periodic_monitoring_consent.updated", id, actor); return updated; }
export function periodicMonitoringConsentAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
