import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type ApplicationProgress = { id: string; business_id: string; application_id: string; application_name: string; status: "In progress" | "Ready for review" | "Needs attention"; current_stage: string; completion: number; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; missing_data: string[]; stages: Array<{ id: string; label: string; status: "Complete" | "In progress" | "Needs attention"; detail: string }>; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let progressRecords: ApplicationProgress[] = [{ id: "progress_demo_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", application_name: "Saraswati Precision Works onboarding", status: "In progress", current_stage: "Document readiness", completion: 72, source_id: "synthetic_onboarding_progress_2026_07", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 86, explanation: "Business identity, Udyam, and core promoter evidence are ready. The application can continue while a current bank statement and refreshed GST filing confirmation are collected.", missing_data: ["Recent business bank statement", "Latest GST filing confirmation"], stages: [{ id: "business", label: "Business profile", status: "Complete", detail: "Business identity and registration context recorded." }, { id: "promoters", label: "Promoter profile", status: "Complete", detail: "Authorised representatives recorded; one source requires refresh." }, { id: "verification", label: "KYB verification", status: "Complete", detail: "Udyam and PAN relationship checks available." }, { id: "documents", label: "Document readiness", status: "Needs attention", detail: "Bank statement and refreshed GST evidence are pending." }, { id: "review", label: "Assisted review", status: "In progress", detail: "Available evidence can be reviewed without autonomous approval." }], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listApplicationProgress() { return progressRecords; }
export function getApplicationProgress(id: string) { return progressRecords.find((record) => record.id === id || record.application_id === id); }
export function createApplicationProgress(input: Pick<ApplicationProgress, "business_id" | "application_id" | "application_name">, actor: string) { const now = new Date().toISOString(); const record: ApplicationProgress = { id: `progress_${crypto.randomUUID()}`, ...input, status: "In progress", current_stage: "Business profile", completion: 0, source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Begin by adding business evidence. Your progress is saved as structured onboarding metadata.", missing_data: ["Business profile", "Consent evidence"], stages: [{ id: "business", label: "Business profile", status: "In progress", detail: "Awaiting business evidence." }], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; progressRecords = [record, ...progressRecords]; writeAudit("application_progress.created", record.id, actor); return record; }
export function updateApplicationProgress(id: string, input: Partial<Pick<ApplicationProgress, "status" | "current_stage">>, actor: string) { const current = getApplicationProgress(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; progressRecords = progressRecords.map((record) => record.id === current.id ? updated : record); writeAudit("application_progress.updated", current.id, actor); return updated; }
export function applicationProgressAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
