import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type BureauStatus = "Connected" | "Needs consent" | "Sync failed";
export type BureauConnector = { id: string; business_name: string; masked_reference: string; purpose: string; status: BureauStatus; consent_status: "Recorded" | "Missing"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; last_sync_at?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type BureauSyncJob = { id: string; connector_id: string; status: "Completed" | "Needs review" | "Failed"; completed_at: string; source_id: string; summary: string };
export type BureauSourceSnapshot = { id: string; connector_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; credit_summary: string; coverage_summary: string; immutable: true };
let connectors: BureauConnector[] = [{ id: "bureau_connector_demo_001", business_name: "Saraswati Precision Works", masked_reference: "BUREAU-••••••-1638", purpose: "Financial health credit-history review", status: "Connected", consent_status: "Recorded", source_id: "synthetic_bureau_connector_2026_07", source_observed_at: "2026-07-13T10:00:00.000Z", freshness: "Current", completeness: 89, explanation: "The connector provides a redacted, explainable credit-history summary for assisted review. No full bureau report or sensitive account identifiers are displayed.", last_sync_at: "2026-07-13T09:55:00.000Z", created_at: "2026-06-20T09:30:00.000Z", updated_at: "2026-07-13T10:00:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }, { id: "bureau_connector_demo_002", business_name: "Saraswati Precision Works", masked_reference: "BUREAU-••••••-1638", purpose: "Default-risk credit-history refresh", status: "Needs consent", consent_status: "Missing", source_id: "synthetic_bureau_connector_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 55, explanation: "A separate purpose-limited consent is required before redacted bureau evidence may support this refresh review.", created_at: "2026-06-30T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const syncJobs: BureauSyncJob[] = [{ id: "bureau_sync_demo_001", connector_id: "bureau_connector_demo_001", status: "Completed", completed_at: "2026-07-13T09:55:00.000Z", source_id: "synthetic_bureau_summary_2026_07", summary: "Latest redacted credit-history summary received." }]; const snapshots: BureauSourceSnapshot[] = [{ id: "bureau_snapshot_demo_001", connector_id: "bureau_connector_demo_001", source_id: "synthetic_bureau_summary_2026_07", observed_at: "2026-07-13T09:55:00.000Z", freshness: "Current", completeness: 89, credit_summary: "The synthetic summary indicates established credit history and no decision recommendation. Analyst review is still required.", coverage_summary: "A redacted coverage summary is available; raw bureau reports, scores, and account identifiers are excluded.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getBureauConnectors() { return { connectors, sync_jobs: syncJobs, source_snapshots: snapshots }; } export function getBureauConnector(id: string) { return connectors.find((connector) => connector.id === id); }
export function createBureauConnector(input: Pick<BureauConnector, "business_name" | "purpose" | "masked_reference">, actor: string) { const now = new Date().toISOString(); const connector: BureauConnector = { id: `bureau_connector_${crypto.randomUUID()}`, ...input, status: "Needs consent", consent_status: "Missing", source_id: "synthetic_bureau_connector_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Record purpose-limited consent to retrieve a synthetic bureau summary. Raw reports and sensitive account data are not stored or displayed.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; connectors = [connector, ...connectors]; writeAudit("bureau_connector.created", connector.id, actor); return connector; }
export function updateBureauConnector(id: string, status: BureauStatus, actor: string) { const current = getBureauConnector(id); if (!current) return undefined; const now = new Date().toISOString(); const connected = status === "Connected"; const updated = { ...current, status, consent_status: connected ? "Recorded" as const : current.consent_status, freshness: status === "Sync failed" ? "Stale" as const : current.freshness, last_sync_at: connected ? now : current.last_sync_at, updated_at: now, updated_by: actor }; connectors = connectors.map((connector) => connector.id === id ? updated : connector); writeAudit("bureau_connector.updated", id, actor); return updated; }
export function bureauConnectorAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
