import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };

export type BusinessProfile = { id: string; legal_name: string; trade_name: string; application_id: string; business_type: string; industry: string; registration_status: "Verified" | "Pending review"; operational_since: string; registered_address: string; consent_status: "Recorded" | "Pending"; promoters: Array<{ id: string; name: string; role: string; verification: "Verified" | "Pending" }>; kyb: { status: "Verified" | "Needs review"; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string }; documents: Array<{ id: string; name: string; status: "Available" | "Missing"; source_id: string; observed_at: string; freshness: "Current" | "Stale" }>; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let profiles: BusinessProfile[] = [{ id: "business_demo_saraswati", legal_name: "Saraswati Precision Works Private Limited", trade_name: "Saraswati Precision Works", application_id: "app_demo_001", business_type: "Private limited company", industry: "Precision engineering", registration_status: "Verified", operational_since: "2018", registered_address: "Pimpri Industrial Estate, Pune, Maharashtra", consent_status: "Recorded", promoters: [{ id: "promoter_demo_001", name: "Anita Kulkarni", role: "Managing director", verification: "Verified" }, { id: "promoter_demo_002", name: "Rohan Kulkarni", role: "Director", verification: "Verified" }], kyb: { status: "Verified", source_id: "synthetic_kyb_2026_07", observed_at: "2026-07-11T10:15:00.000Z", freshness: "Current", completeness: 100, explanation: "Entity registration and authorised representatives match the supplied synthetic onboarding evidence." }, documents: [{ id: "doc_demo_pan", name: "PAN verification", status: "Available", source_id: "synthetic_kyb_2026_07", observed_at: "2026-07-11T10:15:00.000Z", freshness: "Current" }, { id: "doc_demo_gst", name: "GST registration summary", status: "Available", source_id: "synthetic_gst_2026_06", observed_at: "2026-06-30T18:30:00.000Z", freshness: "Stale" }, { id: "doc_demo_bank", name: "Business bank statement", status: "Missing", source_id: "onboarding_checklist_2026_07", observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current" }], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listBusinessProfiles() { return profiles; }
export function getBusinessProfile(id: string) { return profiles.find((profile) => profile.id === id || profile.application_id === id); }
export function createBusinessProfile(input: Pick<BusinessProfile, "legal_name" | "trade_name" | "business_type" | "industry">, actor: string) { const now = new Date().toISOString(); const profile: BusinessProfile = { id: `business_${crypto.randomUUID()}`, application_id: `app_${crypto.randomUUID()}`, ...input, registration_status: "Pending review", operational_since: "Not provided", registered_address: "Not provided", consent_status: "Pending", promoters: [], kyb: { status: "Needs review", source_id: "manual_onboarding", observed_at: now, freshness: "Current", completeness: 0, explanation: "Awaiting supporting onboarding evidence." }, documents: [], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; profiles = [profile, ...profiles]; writeAudit("business_profile.created", profile.id, actor); return profile; }
export function updateBusinessProfile(id: string, input: Partial<Pick<BusinessProfile, "trade_name" | "industry" | "registered_address" | "consent_status">>, actor: string) { const current = getBusinessProfile(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; profiles = profiles.map((profile) => profile.id === current.id ? updated : profile); writeAudit("business_profile.updated", current.id, actor); return updated; }
export function businessProfileAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
