import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";

export { apiError, getActor, isAllowedRole, traceId };

export type BusinessAddress = { id: string; business_id: string; application_id: string; address_type: "Registered" | "Operating"; address_line: string; locality: string; city: string; state: string; postal_code: string; verification_status: "Verified" | "Needs review"; consent_status: "Recorded" | "Pending"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; missing_data: string[]; created_at: string; updated_at: string; created_by: string; updated_by: string; };

let addresses: BusinessAddress[] = [
  { id: "address_demo_registered_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", address_type: "Registered", address_line: "Plot 18, Pimpri Industrial Estate", locality: "Pimpri", city: "Pune", state: "Maharashtra", postal_code: "411018", verification_status: "Verified", consent_status: "Recorded", source_id: "synthetic_gstin_2026_07", source_observed_at: "2026-07-11T10:20:00.000Z", freshness: "Current", completeness: 100, explanation: "The registered address is consistent across the synthetic GSTIN and KYB records supplied for assisted onboarding.", missing_data: [], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-11T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "address_demo_operating_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", address_type: "Operating", address_line: "Unit 6, Bhosari MIDC", locality: "Bhosari", city: "Pune", state: "Maharashtra", postal_code: "411026", verification_status: "Needs review", consent_status: "Recorded", source_id: "synthetic_bank_statement_2026_05", source_observed_at: "2026-05-31T18:30:00.000Z", freshness: "Stale", completeness: 75, explanation: "The operating address appears in synthetic banking evidence, but a recent proof of occupancy is required before it supports an assisted review.", missing_data: ["Current proof of occupancy"], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
];
const auditEvents: Array<Record<string, string>> = [];
export function listBusinessAddresses() { return addresses; }
export function getBusinessAddress(id: string) { return addresses.find((address) => address.id === id); }
export function createBusinessAddress(input: Pick<BusinessAddress, "business_id" | "application_id" | "address_type" | "address_line" | "city" | "state" | "postal_code">, actor: string) { const now = new Date().toISOString(); const address: BusinessAddress = { id: `address_${crypto.randomUUID()}`, ...input, locality: "Not provided", verification_status: "Needs review", consent_status: "Pending", source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Awaiting consent and address evidence from the approved adapter.", missing_data: ["Consent evidence", "Address verification"], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; addresses = [address, ...addresses]; writeAudit("business_address.created", address.id, actor); return address; }
export function updateBusinessAddress(id: string, input: Partial<Pick<BusinessAddress, "address_line" | "locality" | "city" | "state" | "postal_code" | "consent_status">>, actor: string) { const current = getBusinessAddress(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; addresses = addresses.map((address) => address.id === id ? updated : address); writeAudit("business_address.updated", id, actor); return updated; }
export function businessAddressAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
