import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type CkycStatus = "Connected" | "Needs consent" | "Sync failed";
export type CkycConnector = { id: string; business_name: string; masked_reference: string; purpose: string; status: CkycStatus; consent_status: "Recorded" | "Missing"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; last_sync_at?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type CkycSyncJob = { id: string; connector_id: string; status: "Completed" | "Needs review" | "Failed"; completed_at: string; source_id: string; summary: string };
export type CkycSourceSnapshot = { id: string; connector_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; verification_summary: string; profile_summary: string; immutable: true };
let connectors: CkycConnector[] = [{ id: "ckyc_connector_demo_001", business_name: "Saraswati Precision Works", masked_reference: "CKYC-••••••-7284", purpose: "KYB identity relationship verification", status: "Connected", consent_status: "Recorded", source_id: "synthetic_ckyc_connector_2026_07", source_observed_at: "2026-07-13T09:45:00.000Z", freshness: "Current", completeness: 93, explanation: "The connector provides a redacted identity-verification summary for assisted KYB review. Full CKYC records and identifiers are not displayed.", last_sync_at: "2026-07-13T09:40:00.000Z", created_at: "2026-06-20T09:30:00.000Z", updated_at: "2026-07-13T09:45:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }, { id: "ckyc_connector_demo_002", business_name: "Saraswati Precision Works", masked_reference: "CKYC-••••••-7284", purpose: "Promoter identity refresh", status: "Needs consent", consent_status: "Missing", source_id: "synthetic_ckyc_connector_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 57, explanation: "A separate purpose-limited consent is required before redacted CKYC evidence may support the refresh review.", created_at: "2026-06-30T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const syncJobs: CkycSyncJob[] = [{ id: "ckyc_sync_demo_001", connector_id: "ckyc_connector_demo_001", status: "Completed", completed_at: "2026-07-13T09:40:00.000Z", source_id: "synthetic_ckyc_summary_2026_07", summary: "Latest redacted identity-verification summary received." }]; const snapshots: CkycSourceSnapshot[] = [{ id: "ckyc_snapshot_demo_001", connector_id: "ckyc_connector_demo_001", source_id: "synthetic_ckyc_summary_2026_07", observed_at: "2026-07-13T09:40:00.000Z", freshness: "Current", completeness: 93, verification_summary: "The synthetic identity relationship check is aligned with the available business and promoter evidence.", profile_summary: "A redacted profile summary is available; raw CKYC payloads and full personal identifiers are excluded.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getCkycConnectors() { return { connectors, sync_jobs: syncJobs, source_snapshots: snapshots }; } export function getCkycConnector(id: string) { return connectors.find((connector) => connector.id === id); }
export function createCkycConnector(input: Pick<CkycConnector, "business_name" | "purpose" | "masked_reference">, actor: string) { const now = new Date().toISOString(); const connector: CkycConnector = { id: `ckyc_connector_${crypto.randomUUID()}`, ...input, status: "Needs consent", consent_status: "Missing", source_id: "synthetic_ckyc_connector_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Record purpose-limited consent to retrieve a synthetic CKYC verification summary. Raw personal data is not stored or displayed.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; connectors = [connector, ...connectors]; writeAudit("ckyc_connector.created", connector.id, actor); return connector; }
export function updateCkycConnector(id: string, status: CkycStatus, actor: string) { const current = getCkycConnector(id); if (!current) return undefined; const now = new Date().toISOString(); const connected = status === "Connected"; const updated = { ...current, status, consent_status: connected ? "Recorded" as const : current.consent_status, freshness: status === "Sync failed" ? "Stale" as const : current.freshness, last_sync_at: connected ? now : current.last_sync_at, updated_at: now, updated_by: actor }; connectors = connectors.map((connector) => connector.id === id ? updated : connector); writeAudit("ckyc_connector.updated", id, actor); return updated; }
export function ckycConnectorAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
