import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type SyncStatus = "Completed" | "Needs review" | "Failed";
export type ConnectorSyncLog = { id: string; connector_name: string; connector_type: string; status: SyncStatus; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; summary: string; redaction: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
let syncLogs: ConnectorSyncLog[] = [{ id: "sync_log_demo_001", connector_name: "GST adapter", connector_type: "Turnover summaries", status: "Completed", source_id: "synthetic_gst_summary_2026_07", observed_at: "2026-07-13T08:55:00.000Z", freshness: "Current", completeness: 88, summary: "Synthetic turnover and filing summary refreshed successfully.", redaction: "Raw GST returns and identifiers are not logged.", created_at: "2026-07-13T08:55:00.000Z", updated_at: "2026-07-13T08:55:00.000Z", created_by: "system.seed", updated_by: "system.seed" }, { id: "sync_log_demo_002", connector_name: "UPI collections adapter", connector_type: "Collections trends", status: "Needs review", source_id: "synthetic_upi_summary_2026_06", observed_at: "2026-06-30T16:00:00.000Z", freshness: "Stale", completeness: 74, summary: "Latest collection summary needs renewed consent before refresh.", redaction: "Payer and raw transaction details are not logged.", created_at: "2026-06-30T16:00:00.000Z", updated_at: "2026-06-30T16:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }, { id: "sync_log_demo_003", connector_name: "Mock data adapter", connector_type: "Synthetic evidence", status: "Completed", source_id: "synthetic_bundle_2026_07", observed_at: "2026-07-13T10:30:00.000Z", freshness: "Current", completeness: 90, summary: "Source-linked synthetic evidence bundle generated for prototype review.", redaction: "No raw external payloads are present.", created_at: "2026-07-13T10:30:00.000Z", updated_at: "2026-07-13T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" }]; const auditEvents: Array<Record<string, string>> = [];
export function listConnectorSyncLogs() { return syncLogs; } export function getConnectorSyncLog(id: string) { return syncLogs.find((log) => log.id === id); }
export function createConnectorSyncLog(input: Pick<ConnectorSyncLog, "connector_name" | "connector_type" | "summary">, actor: string) { const now = new Date().toISOString(); const log: ConnectorSyncLog = { id: `sync_log_${crypto.randomUUID()}`, ...input, status: "Needs review", source_id: "synthetic_manual_sync", observed_at: now, freshness: "Current", completeness: 0, redaction: "No raw sensitive payloads are logged.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; syncLogs = [log, ...syncLogs]; writeAudit("connector_sync_log.created", log.id, actor); return log; }
export function updateConnectorSyncLog(id: string, status: SyncStatus, actor: string) { const current = getConnectorSyncLog(id); if (!current) return undefined; const updated = { ...current, status, freshness: status === "Failed" ? "Stale" as const : current.freshness, updated_at: new Date().toISOString(), updated_by: actor }; syncLogs = syncLogs.map((log) => log.id === id ? updated : log); writeAudit("connector_sync_log.updated", id, actor); return updated; }
export function connectorSyncLogAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
