import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type DemoScenario = { id: string; name: string; audience: "MSME owner" | "Bank analyst" | "Risk & compliance"; journey: string; status: "Demo ready" | "Needs review"; confidence: number; recommendation: string; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let scenarios: DemoScenario[] = [
  { id: "scenario_owner_001", name: "New-to-credit manufacturer", audience: "MSME owner", journey: "Guided evidence readiness", status: "Demo ready", confidence: 90, recommendation: "Show how verified business details and permitted digital collections build a clearer credit-readiness story.", explanation: "The journey uses only synthetic data and supportive borrower copy; no credit decision is made.", source_id: "demo_script_owner_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 100, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "scenario_analyst_001", name: "Assisted Financial Health Card review", audience: "Bank analyst", journey: "Evidence-led analyst review", status: "Demo ready", confidence: 87, recommendation: "Show the analyst confidence, freshness, and missing-data indicators before an assisted next step.", explanation: "Evidence is source-linked and explainable; stale GST coverage remains visibly flagged.", source_id: "demo_script_analyst_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 95, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "scenario_risk_001", name: "Early-warning governance review", audience: "Risk & compliance", journey: "Explainable stress-signal review", status: "Needs review", confidence: 73, recommendation: "State clearly that the prediction signal is synthetic decision support, not production model validation.", explanation: "The scenario requires a freshness review before governance demonstration because its policy snapshot is stale.", source_id: "demo_script_risk_v1", source_observed_at: "2026-05-21T08:00:00.000Z", freshness: "Stale", completeness: 70, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
]; const audits: Array<Record<string, string>> = [];
export function listScenarios() { return scenarios; } export function getScenario(id: string) { return scenarios.find((scenario) => scenario.id === id); }
export function createScenario(input: Pick<DemoScenario, "name" | "audience" | "journey" | "recommendation" | "explanation">, actor: string) { const now = new Date().toISOString(); const scenario: DemoScenario = { id: `scenario_${crypto.randomUUID()}`, ...input, status: "Needs review", confidence: 0, source_id: "manual_scenario_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; scenarios = [scenario, ...scenarios]; audit("demo_scenario.created", scenario.id, actor); return scenario; }
export function updateScenario(id: string, input: Partial<Pick<DemoScenario, "name" | "journey" | "recommendation" | "explanation" | "status">>, actor: string) { const current = getScenario(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; scenarios = scenarios.map((scenario) => scenario.id === id ? updated : scenario); audit("demo_scenario.updated", id, actor); return updated; }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function scenarioAuditEventCount() { return audits.length; }
