import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type UploadedDocument = { id: string; business_id: string; application_id: string; document_type: string; file_label: string; upload_status: "Available" | "Missing" | "Rejected"; review_status: "Verified" | "Needs review"; consent_status: "Recorded" | "Pending"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; missing_data: string[]; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let documents: UploadedDocument[] = [{ id: "document_demo_pan_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", document_type: "PAN verification", file_label: "PAN verification receipt", upload_status: "Available", review_status: "Verified", consent_status: "Recorded", source_id: "synthetic_document_intake_2026_07", source_observed_at: "2026-07-11T10:18:00.000Z", freshness: "Current", completeness: 100, explanation: "A synthetic PAN verification receipt is available and aligns with the business identity record. Raw document content is not retained in this demo.", missing_data: [], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-11T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" }, { id: "document_demo_bank_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", document_type: "Business bank statement", file_label: "No file received", upload_status: "Missing", review_status: "Needs review", consent_status: "Pending", source_id: "onboarding_checklist_2026_07", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 0, explanation: "A current business bank statement is still needed. Upload a recent statement when ready; the assisted review can continue with the available evidence.", missing_data: ["Recent business bank statement", "Consent evidence"], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }, { id: "document_demo_gst_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", document_type: "GST registration summary", file_label: "GST registration summary", upload_status: "Available", review_status: "Needs review", consent_status: "Recorded", source_id: "synthetic_document_intake_2026_05", source_observed_at: "2026-05-31T18:30:00.000Z", freshness: "Stale", completeness: 75, explanation: "The synthetic GST registration summary is available, but the associated source is stale and should be refreshed before assisted credit review.", missing_data: ["Latest GST filing confirmation"], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listUploadedDocuments() { return documents; }
export function getUploadedDocument(id: string) { return documents.find((document) => document.id === id); }
export function createUploadedDocument(input: Pick<UploadedDocument, "business_id" | "application_id" | "document_type" | "file_label">, actor: string) { const now = new Date().toISOString(); const document: UploadedDocument = { id: `document_${crypto.randomUUID()}`, ...input, upload_status: "Available", review_status: "Needs review", consent_status: "Pending", source_id: "mock_document_upload", source_observed_at: now, freshness: "Current", completeness: 50, explanation: "Upload metadata was recorded in the synthetic adapter. The file itself is not stored in this prototype.", missing_data: ["Consent evidence", "Analyst review"], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; documents = [document, ...documents]; writeAudit("documents_upload.created", document.id, actor); return document; }
export function updateUploadedDocument(id: string, input: Partial<Pick<UploadedDocument, "upload_status" | "consent_status">>, actor: string) { const current = getUploadedDocument(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; documents = documents.map((document) => document.id === id ? updated : document); writeAudit("documents_upload.updated", id, actor); return updated; }
export function documentsUploadAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
