import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type EpfoStatus = "Connected" | "Needs consent" | "Sync failed";
export type EpfoPayrollConnector = { id: string; business_name: string; masked_establishment_id: string; purpose: string; status: EpfoStatus; consent_status: "Recorded" | "Missing"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; last_sync_at?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type EpfoSyncJob = { id: string; connector_id: string; status: "Completed" | "Needs review" | "Failed"; completed_at: string; source_id: string; summary: string };
export type EpfoSourceSnapshot = { id: string; connector_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; payroll_summary: string; compliance_summary: string; immutable: true };
let connectors: EpfoPayrollConnector[] = [{ id: "epfo_connector_demo_001", business_name: "Saraswati Precision Works", masked_establishment_id: "MH/•••••/4812", purpose: "Financial health payroll stability review", status: "Connected", consent_status: "Recorded", source_id: "synthetic_epfo_connector_2026_07", source_observed_at: "2026-07-13T09:30:00.000Z", freshness: "Current", completeness: 86, explanation: "The connector provides aggregated payroll continuity and filing summaries for assisted review. Employee-level information is not displayed.", last_sync_at: "2026-07-13T09:25:00.000Z", created_at: "2026-06-20T09:30:00.000Z", updated_at: "2026-07-13T09:30:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }, { id: "epfo_connector_demo_002", business_name: "Saraswati Precision Works", masked_establishment_id: "MH/•••••/4812", purpose: "Default-risk workforce monitoring", status: "Needs consent", consent_status: "Missing", source_id: "synthetic_epfo_connector_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 51, explanation: "A separate purpose-limited consent is required before aggregated payroll summaries may support monitoring evidence.", created_at: "2026-06-30T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const syncJobs: EpfoSyncJob[] = [{ id: "epfo_sync_demo_001", connector_id: "epfo_connector_demo_001", status: "Completed", completed_at: "2026-07-13T09:25:00.000Z", source_id: "synthetic_epfo_summary_2026_07", summary: "Latest aggregated payroll continuity summary received." }]; const snapshots: EpfoSourceSnapshot[] = [{ id: "epfo_snapshot_demo_001", connector_id: "epfo_connector_demo_001", source_id: "synthetic_epfo_summary_2026_07", observed_at: "2026-07-13T09:25:00.000Z", freshness: "Current", completeness: 86, payroll_summary: "The latest available summary indicates a stable workforce contribution pattern across three reporting periods.", compliance_summary: "Two of the latest three filing confirmations are available; one confirmation requires refresh.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getEpfoPayrollConnectors() { return { connectors, sync_jobs: syncJobs, source_snapshots: snapshots }; } export function getEpfoPayrollConnector(id: string) { return connectors.find((connector) => connector.id === id); }
export function createEpfoPayrollConnector(input: Pick<EpfoPayrollConnector, "business_name" | "purpose" | "masked_establishment_id">, actor: string) { const now = new Date().toISOString(); const connector: EpfoPayrollConnector = { id: `epfo_connector_${crypto.randomUUID()}`, ...input, status: "Needs consent", consent_status: "Missing", source_id: "synthetic_epfo_connector_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Record purpose-limited consent to retrieve a synthetic payroll summary. Employee-level data is not stored or displayed.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; connectors = [connector, ...connectors]; writeAudit("epfo_payroll_connector.created", connector.id, actor); return connector; }
export function updateEpfoPayrollConnector(id: string, status: EpfoStatus, actor: string) { const current = getEpfoPayrollConnector(id); if (!current) return undefined; const now = new Date().toISOString(); const connected = status === "Connected"; const updated = { ...current, status, consent_status: connected ? "Recorded" as const : current.consent_status, freshness: status === "Sync failed" ? "Stale" as const : current.freshness, last_sync_at: connected ? now : current.last_sync_at, updated_at: now, updated_by: actor }; connectors = connectors.map((connector) => connector.id === id ? updated : connector); writeAudit("epfo_payroll_connector.updated", id, actor); return updated; }
export function epfoPayrollConnectorAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
