import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type FeaturePriority = { id: string; feature: string; track: "Track 03" | "Track 04" | "Shared"; priority: "P1" | "P2" | "P3"; score: number; status: "Ready" | "Needs review"; recommendation: string; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let priorities: FeaturePriority[] = [
  { id: "priority_fhc_001", feature: "Financial Health Card evidence pack", track: "Track 03", priority: "P1", score: 91, status: "Ready", recommendation: "Prioritize because it delivers consistent borrower evidence and faster analyst review in one vertical slice.", explanation: "High user value, direct support for assisted review, and a clear synthetic-data path make this the leading delivery candidate.", source_id: "priority_rubric_fhc_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 98, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "priority_ew_001", feature: "Explainable early-warning signals", track: "Track 04", priority: "P1", score: 84, status: "Ready", recommendation: "Prioritize as decision support with clear governance language and no autonomous credit action.", explanation: "It addresses earlier stress detection while retaining analyst-led, explainable review boundaries.", source_id: "priority_rubric_ew_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 91, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "priority_connector_001", feature: "Partner sandbox connectors", track: "Shared", priority: "P2", score: 63, status: "Needs review", recommendation: "Defer until sandbox authorization and refreshed connector readiness evidence are available.", explanation: "The adapter contract is planned, but live GST, UPI, AA, and OCEN calls remain outside the current scope.", source_id: "priority_rubric_connectors_v1", source_observed_at: "2026-05-14T08:00:00.000Z", freshness: "Stale", completeness: 61, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
]; const audits: Array<Record<string, string>> = [];
export function listPriorities() { return priorities; } export function getPriority(id: string) { return priorities.find((item) => item.id === id); }
export function createPriority(input: Pick<FeaturePriority, "feature" | "track" | "priority" | "recommendation" | "explanation">, actor: string) { const now = new Date().toISOString(); const item: FeaturePriority = { id: `priority_${crypto.randomUUID()}`, ...input, score: 0, status: "Needs review", source_id: "manual_priority_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; priorities = [item, ...priorities]; audit("feature_priority.created", item.id, actor); return item; }
export function updatePriority(id: string, input: Partial<Pick<FeaturePriority, "feature" | "priority" | "recommendation" | "explanation" | "status">>, actor: string) { const current = getPriority(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; priorities = priorities.map((item) => item.id === id ? updated : item); audit("feature_priority.updated", id, actor); return updated; }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function priorityAuditEventCount() { return audits.length; }
