import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type GstrStatus = "Connected" | "Needs consent" | "Sync failed";
export type GstConnector = { id: string; business_name: string; masked_gstin: string; purpose: string; status: GstrStatus; consent_status: "Recorded" | "Missing"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; last_sync_at?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type GstSyncJob = { id: string; connector_id: string; status: "Completed" | "Needs review" | "Failed"; completed_at: string; source_id: string; summary: string };
export type GstSourceSnapshot = { id: string; connector_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; turnover_summary: string; filing_summary: string; immutable: true };
let connectors: GstConnector[] = [{ id: "gst_connector_demo_001", business_name: "Saraswati Precision Works", masked_gstin: "27AAAAA••••1Z5", purpose: "Financial health turnover verification", status: "Connected", consent_status: "Recorded", source_id: "synthetic_gst_connector_2026_07", source_observed_at: "2026-07-13T09:00:00.000Z", freshness: "Current", completeness: 88, explanation: "The connector provides filing and turnover summaries for an assisted financial health review. Full GST returns and identifiers are not displayed.", last_sync_at: "2026-07-13T08:55:00.000Z", created_at: "2026-06-18T09:30:00.000Z", updated_at: "2026-07-13T09:00:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }, { id: "gst_connector_demo_002", business_name: "Saraswati Precision Works", masked_gstin: "27AAAAA••••1Z5", purpose: "Default-risk early warning review", status: "Needs consent", consent_status: "Missing", source_id: "synthetic_gst_connector_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 54, explanation: "A separate purpose-limited consent is required before GST summaries may support monitoring evidence.", created_at: "2026-06-30T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const syncJobs: GstSyncJob[] = [{ id: "gst_sync_demo_001", connector_id: "gst_connector_demo_001", status: "Completed", completed_at: "2026-07-13T08:55:00.000Z", source_id: "synthetic_gst_summary_2026_07", summary: "Latest turnover and filing summary received." }];
const snapshots: GstSourceSnapshot[] = [{ id: "gst_snapshot_demo_001", connector_id: "gst_connector_demo_001", source_id: "synthetic_gst_summary_2026_07", observed_at: "2026-07-13T08:55:00.000Z", freshness: "Current", completeness: 88, turnover_summary: "₹18.40 lakh reported turnover over the latest available three-month summary.", filing_summary: "Two of the latest three filing summaries are available; one filing confirmation requires refresh.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getGstConnectors() { return { connectors, sync_jobs: syncJobs, source_snapshots: snapshots }; } export function getGstConnector(id: string) { return connectors.find((connector) => connector.id === id); }
export function createGstConnector(input: Pick<GstConnector, "business_name" | "purpose" | "masked_gstin">, actor: string) { const now = new Date().toISOString(); const connector: GstConnector = { id: `gst_connector_${crypto.randomUUID()}`, ...input, status: "Needs consent", consent_status: "Missing", source_id: "synthetic_gst_connector_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Record a purpose-limited consent to retrieve a synthetic GST summary. No raw GST payload is stored or displayed.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; connectors = [connector, ...connectors]; writeAudit("gst_connector.created", connector.id, actor); return connector; }
export function updateGstConnector(id: string, status: GstrStatus, actor: string) { const current = getGstConnector(id); if (!current) return undefined; const now = new Date().toISOString(); const connected = status === "Connected"; const updated = { ...current, status, consent_status: connected ? "Recorded" as const : current.consent_status, freshness: status === "Sync failed" ? "Stale" as const : current.freshness, last_sync_at: connected ? now : current.last_sync_at, updated_at: now, updated_by: actor }; connectors = connectors.map((connector) => connector.id === id ? updated : connector); writeAudit("gst_connector.updated", id, actor); return updated; }
export function gstConnectorAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
