import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type IndustryClassification = { id: string; business_id: string; application_id: string; classification_system: "NIC 2008" | "Internal risk taxonomy"; industry_code: string; industry_name: string; classification_status: "Verified" | "Needs review"; confidence: number; consent_status: "Recorded" | "Pending"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; missing_data: string[]; snapshot_id: string; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let classifications: IndustryClassification[] = [
  { id: "industry_demo_nic_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", classification_system: "NIC 2008", industry_code: "25920", industry_name: "Manufacture of light metal packaging", classification_status: "Verified", confidence: 92, consent_status: "Recorded", source_id: "synthetic_udyam_2026_07", source_observed_at: "2026-07-11T10:22:00.000Z", freshness: "Current", completeness: 100, explanation: "The reported activity is consistent with synthetic Udyam registration and the supplied precision-engineering business profile.", missing_data: [], snapshot_id: "snapshot_industry_2026_07_11", created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-11T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "industry_demo_risk_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", classification_system: "Internal risk taxonomy", industry_code: "MFG-PRECISION", industry_name: "Precision engineering and fabricated components", classification_status: "Needs review", confidence: 74, consent_status: "Recorded", source_id: "synthetic_gstin_2026_05", source_observed_at: "2026-05-31T18:30:00.000Z", freshness: "Stale", completeness: 78, explanation: "Transaction descriptors support the classification, but a current GST filing summary is needed before it is used in an assisted risk review.", missing_data: ["Current GST filing summary"], snapshot_id: "snapshot_industry_2026_05_31", created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
];
const auditEvents: Array<Record<string, string>> = [];
export function listIndustryClassifications() { return classifications; }
export function getIndustryClassification(id: string) { return classifications.find((classification) => classification.id === id); }
export function createIndustryClassification(input: Pick<IndustryClassification, "business_id" | "application_id" | "classification_system" | "industry_code" | "industry_name">, actor: string) { const now = new Date().toISOString(); const classification: IndustryClassification = { id: `industry_${crypto.randomUUID()}`, ...input, classification_status: "Needs review", confidence: 0, consent_status: "Pending", source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Awaiting consent and classification evidence from the approved adapter.", missing_data: ["Consent evidence", "Classification source"], snapshot_id: `snapshot_${crypto.randomUUID()}`, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; classifications = [classification, ...classifications]; writeAudit("industry_classification.created", classification.id, actor); return classification; }
export function updateIndustryClassification(id: string, input: Partial<Pick<IndustryClassification, "industry_code" | "industry_name" | "consent_status">>, actor: string) { const current = getIndustryClassification(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; classifications = classifications.map((classification) => classification.id === id ? updated : classification); writeAudit("industry_classification.updated", id, actor); return updated; }
export function industryClassificationAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
