import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type Job = { id: string; title: string; audience: "MSME owner" | "Bank analyst" | "Risk & compliance"; stage: "Now" | "Next"; outcome: string; recommendation: string; confidence: number; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let jobs: Job[] = [
  { id: "job_owner_001", title: "Prove business readiness", audience: "MSME owner", stage: "Now", outcome: "Build a clear, less intimidating path to evidence creditworthiness.", recommendation: "Share verified business details first, then add permitted alternate data when you are ready.", confidence: 92, explanation: "The job starts with supportive, action-oriented borrower copy and never exposes unapproved model detail.", source_id: "jtbd_owner_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 95, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "job_analyst_001", title: "Make a confident assisted review", audience: "Bank analyst", stage: "Now", outcome: "Reach a consistent, explainable recommendation faster.", recommendation: "Review confidence, source freshness, and missing data before escalating the case.", confidence: 89, explanation: "The job pairs evidence with clear confidence and freshness indicators for analyst-led decision support.", source_id: "jtbd_analyst_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 98, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "job_risk_001", title: "Govern decision-support outputs", audience: "Risk & compliance", stage: "Next", outcome: "Maintain reviewable evidence and purpose-limited access.", recommendation: "Validate audit evidence and source freshness before using a synthetic scenario in governance review.", confidence: 74, explanation: "Autonomous decisions and production-model claims remain outside the scope of this job.", source_id: "jtbd_risk_v1", source_observed_at: "2026-05-28T08:00:00.000Z", freshness: "Stale", completeness: 70, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
];
const audits: Array<Record<string, string>> = [];
export function listJobs() { return jobs; } export function getJob(id: string) { return jobs.find((job) => job.id === id); }
export function createJob(input: Pick<Job, "title" | "audience" | "outcome" | "recommendation" | "explanation">, actor: string) { const now = new Date().toISOString(); const job: Job = { id: `job_${crypto.randomUUID()}`, ...input, stage: "Next", confidence: 0, source_id: "manual_job_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; jobs = [job, ...jobs]; audit("jobs_to_be_done.created", job.id, actor); return job; }
export function updateJob(id: string, input: Partial<Pick<Job, "title" | "outcome" | "recommendation" | "explanation" | "stage">>, actor: string) { const current = getJob(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; jobs = jobs.map((job) => job.id === id ? updated : job); audit("jobs_to_be_done.updated", id, actor); return updated; }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function jobAuditEventCount() { return audits.length; }
