import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type KybReviewPacket = { id: string; business_id: string; application_id: string; packet_status: "Ready for analyst review" | "Needs attention" | "Reviewed"; confidence: number; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; recommendation: string; snapshot_id: string; evidence: Array<{ id: string; label: string; status: "Verified" | "Needs review"; source_id: string; freshness: "Current" | "Stale"; detail: string }>; missing_data: string[]; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let packets: KybReviewPacket[] = [{ id: "kyb_packet_demo_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", packet_status: "Ready for analyst review", confidence: 81, source_id: "synthetic_kyb_packet_2026_07", source_observed_at: "2026-07-12T08:15:00.000Z", freshness: "Current", completeness: 84, explanation: "The packet assembles available synthetic business, Udyam, PAN, promoter, document, and onboarding-context evidence. It makes gaps visible for an assisted analyst review.", recommendation: "Proceed to assisted KYB review while requesting the current bank statement and refreshed GST filing confirmation.", snapshot_id: "snapshot_kyb_packet_2026_07_12_001", evidence: [{ id: "business", label: "Business profile", status: "Verified", source_id: "synthetic_kyb_2026_07", freshness: "Current", detail: "Business identity and authorised representatives aligned." }, { id: "udyam", label: "Udyam verification", status: "Verified", source_id: "synthetic_udyam_2026_07", freshness: "Current", detail: "Masked registration reference and enterprise category aligned." }, { id: "pan", label: "PAN relationship", status: "Verified", source_id: "synthetic_pan_2026_07", freshness: "Current", detail: "Masked PAN relationship aligned with business identity." }, { id: "gst", label: "GST evidence", status: "Needs review", source_id: "synthetic_gstin_2026_05", freshness: "Stale", detail: "Latest filing confirmation needs refresh." }, { id: "documents", label: "Document readiness", status: "Needs review", source_id: "onboarding_checklist_2026_07", freshness: "Current", detail: "Current business bank statement is still needed." }], missing_data: ["Recent business bank statement", "Latest GST filing confirmation"], created_at: "2026-07-12T08:15:00.000Z", updated_at: "2026-07-12T08:15:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listKybReviewPackets() { return packets; }
export function getKybReviewPacket(id: string) { return packets.find((packet) => packet.id === id || packet.application_id === id); }
export function createKybReviewPacket(input: Pick<KybReviewPacket, "business_id" | "application_id">, actor: string) { const now = new Date().toISOString(); const packet: KybReviewPacket = { id: `kyb_packet_${crypto.randomUUID()}`, ...input, packet_status: "Needs attention", confidence: 0, source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "A packet will be assembled as purpose-limited onboarding evidence becomes available.", recommendation: "Complete business identity and consent evidence before analyst review.", snapshot_id: `snapshot_${crypto.randomUUID()}`, evidence: [], missing_data: ["Business identity evidence", "Consent evidence"], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; packets = [packet, ...packets]; writeAudit("kyb_review_packet.created", packet.id, actor); return packet; }
export function updateKybReviewPacket(id: string, input: Partial<Pick<KybReviewPacket, "packet_status">>, actor: string) { const current = getKybReviewPacket(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; packets = packets.map((packet) => packet.id === current.id ? updated : packet); writeAudit("kyb_review_packet.updated", current.id, actor); return updated; }
export function kybReviewPacketAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
