import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type MockAdapterStatus = "Ready" | "Needs review" | "Disabled";
export type MockDataAdapter = { id: string; name: string; domain: string; status: MockAdapterStatus; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; redaction: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type MockSyncJob = { id: string; adapter_id: string; status: "Completed" | "Needs review" | "Failed"; completed_at: string; source_id: string; summary: string };
export type MockSourceSnapshot = { id: string; adapter_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; summary: string; immutable: true };
let adapters: MockDataAdapter[] = [{ id: "mock_adapter_demo_001", name: "Synthetic alternate-data bundle", domain: "Financial health assessment", status: "Ready", source_id: "synthetic_bundle_2026_07", source_observed_at: "2026-07-13T10:30:00.000Z", freshness: "Current", completeness: 90, explanation: "A deterministic synthetic bundle supports safe prototype demonstrations across consented connectors without external sandbox access.", redaction: "No raw external payloads or personal identifiers are included.", created_at: "2026-07-13T10:30:00.000Z", updated_at: "2026-07-13T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" }, { id: "mock_adapter_demo_002", name: "Synthetic stress scenario", domain: "Default-risk review", status: "Needs review", source_id: "synthetic_stress_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 68, explanation: "The scenario demonstrates a known data gap for analyst review and should be refreshed before a demo assessment.", redaction: "No raw external payloads or personal identifiers are included.", created_at: "2026-06-30T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const syncJobs: MockSyncJob[] = [{ id: "mock_sync_demo_001", adapter_id: "mock_adapter_demo_001", status: "Completed", completed_at: "2026-07-13T10:30:00.000Z", source_id: "synthetic_bundle_2026_07", summary: "Synthetic source-linked evidence bundle generated." }]; const snapshots: MockSourceSnapshot[] = [{ id: "mock_snapshot_demo_001", adapter_id: "mock_adapter_demo_001", source_id: "synthetic_bundle_2026_07", observed_at: "2026-07-13T10:30:00.000Z", freshness: "Current", completeness: 90, summary: "Immutable synthetic evidence snapshot for prototype testing; it is not production evidence or a credit decision input.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getMockDataAdapters() { return { adapters, sync_jobs: syncJobs, source_snapshots: snapshots }; } export function getMockDataAdapter(id: string) { return adapters.find((adapter) => adapter.id === id); }
export function createMockDataAdapter(input: Pick<MockDataAdapter, "name" | "domain">, actor: string) { const now = new Date().toISOString(); const adapter: MockDataAdapter = { id: `mock_adapter_${crypto.randomUUID()}`, ...input, status: "Needs review", source_id: "synthetic_custom_adapter", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "A synthetic adapter has been registered and requires configuration review before its summaries can be used.", redaction: "No raw external payloads or personal identifiers are included.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; adapters = [adapter, ...adapters]; writeAudit("mock_data_adapter.created", adapter.id, actor); return adapter; }
export function updateMockDataAdapter(id: string, status: MockAdapterStatus, actor: string) { const current = getMockDataAdapter(id); if (!current) return undefined; const updated = { ...current, status, freshness: status === "Needs review" ? "Stale" as const : current.freshness, updated_at: new Date().toISOString(), updated_by: actor }; adapters = adapters.map((adapter) => adapter.id === id ? updated : adapter); writeAudit("mock_data_adapter.updated", id, actor); return updated; }
export function mockDataAdapterAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
