import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type NorthStarMetric = { id: string; name: string; track: "Track 03" | "Track 04" | "Shared"; value: string; target: string; status: "On track" | "Needs review"; confidence: number; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let metrics: NorthStarMetric[] = [
  { id: "metric_onboard_001", name: "Evidence-ready MSME journeys", track: "Track 03", value: "68%", target: "75%", status: "On track", confidence: 87, explanation: "Synthetic demo journeys complete an explainable evidence pack without requiring a live connector.", source_id: "demo_metric_onboard_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 94, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "metric_review_001", name: "Assisted analyst review time", track: "Shared", value: "18 min", target: "≤ 20 min", status: "On track", confidence: 84, explanation: "Source-linked evidence, confidence, and missing-data indicators reduce review ambiguity in the synthetic workflow.", source_id: "demo_metric_review_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 90, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "metric_stress_001", name: "Early stress signals explained", track: "Track 04", value: "62%", target: "70%", status: "Needs review", confidence: 71, explanation: "This is a synthetic decision-support coverage signal, not a production default-prediction validation claim.", source_id: "demo_metric_stress_v1", source_observed_at: "2026-05-22T08:00:00.000Z", freshness: "Stale", completeness: 68, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
]; const audits: Array<Record<string, string>> = [];
export function listMetrics() { return metrics; } export function getMetric(id: string) { return metrics.find((metric) => metric.id === id); }
export function createMetric(input: Pick<NorthStarMetric, "name" | "track" | "value" | "target" | "explanation">, actor: string) { const now = new Date().toISOString(); const metric: NorthStarMetric = { id: `metric_${crypto.randomUUID()}`, ...input, status: "Needs review", confidence: 0, source_id: "manual_metric_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; metrics = [metric, ...metrics]; audit("north_star_metric.created", metric.id, actor); return metric; }
export function updateMetric(id: string, input: Partial<Pick<NorthStarMetric, "name" | "value" | "target" | "explanation" | "status">>, actor: string) { const current = getMetric(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; metrics = metrics.map((metric) => metric.id === id ? updated : metric); audit("north_star_metric.updated", id, actor); return updated; }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function metricAuditEventCount() { return audits.length; }
