import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type NtbNtcIdentification = { id: string; business_id: string; application_id: string; segment: "New to Bank (NTB)" | "New to Credit (NTC)" | "Established relationship"; status: "Ready for review" | "Needs review"; confidence: number; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; evidence: string[]; missing_data: string[]; snapshot_id: string; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let identifications: NtbNtcIdentification[] = [{ id: "ntb_ntc_demo_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", segment: "New to Bank (NTB)", status: "Ready for review", confidence: 84, source_id: "synthetic_onboarding_signals_2026_07", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 82, explanation: "Available synthetic onboarding evidence indicates no existing relationship in the demo bank profile. This segment is a review aid, not a credit decision or bureau finding.", evidence: ["Verified business identity and Udyam context", "No existing synthetic bank relationship record", "Promoter and document intake evidence available"], missing_data: ["Recent business bank statement"], snapshot_id: "snapshot_ntb_ntc_2026_07_12_001", created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listNtbNtcIdentifications() { return identifications; }
export function getNtbNtcIdentification(id: string) { return identifications.find((item) => item.id === id || item.application_id === id); }
export function createNtbNtcIdentification(input: Pick<NtbNtcIdentification, "business_id" | "application_id" | "segment">, actor: string) { const now = new Date().toISOString(); const item: NtbNtcIdentification = { id: `ntb_ntc_${crypto.randomUUID()}`, ...input, status: "Needs review", confidence: 0, source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Awaiting purpose-limited onboarding evidence for assisted segmentation review.", evidence: [], missing_data: ["Business identity evidence", "Consent evidence"], snapshot_id: `snapshot_${crypto.randomUUID()}`, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; identifications = [item, ...identifications]; writeAudit("ntb_ntc_identification.created", item.id, actor); return item; }
export function updateNtbNtcIdentification(id: string, input: Partial<Pick<NtbNtcIdentification, "segment" | "status">>, actor: string) { const current = getNtbNtcIdentification(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; identifications = identifications.map((item) => item.id === current.id ? updated : item); writeAudit("ntb_ntc_identification.updated", current.id, actor); return updated; }
export function ntbNtcIdentificationAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
