import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type OperatingPrinciple = { id: string; principle: string; focus: "Borrower trust" | "Analyst clarity" | "Governance"; commitment: string; status: "Active" | "Review required"; confidence: number; recommendation: string; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let principles: OperatingPrinciple[] = [
  { id: "principle_consent_001", principle: "Evidence is permissioned and purposeful", focus: "Borrower trust", commitment: "Ask only for permitted evidence and explain the next step in plain, supportive language.", status: "Active", confidence: 93, recommendation: "Keep consent evidence attached to every external or alternate-data workflow.", explanation: "Borrowers see approved explanations, never raw sensitive payloads or unapproved model internals.", source_id: "operating_principle_consent_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 100, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "principle_explain_001", principle: "Recommendations remain reviewable", focus: "Analyst clarity", commitment: "Pair every score or recommendation with source-linked evidence, confidence, freshness, and missing-data indicators.", status: "Active", confidence: 89, recommendation: "Maintain an assisted-review boundary for every credit-relevant recommendation.", explanation: "Analyst outputs are consistent and explainable, but do not autonomously approve credit.", source_id: "operating_principle_explain_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 96, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "principle_audit_001", principle: "Decision-impacting changes are traceable", focus: "Governance", commitment: "Preserve immutable audit events for configuration, scores, consent, predictions, and reports.", status: "Review required", confidence: 76, recommendation: "Refresh the synthetic governance policy snapshot before presenting it as current controls evidence.", explanation: "Purpose-limited access and audit evidence make controls reviewable without exposing sensitive data.", source_id: "operating_principle_audit_v1", source_observed_at: "2026-05-19T08:00:00.000Z", freshness: "Stale", completeness: 73, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
]; const audits: Array<Record<string, string>> = [];
export function listPrinciples() { return principles; } export function getPrinciple(id: string) { return principles.find((item) => item.id === id); }
export function createPrinciple(input: Pick<OperatingPrinciple, "principle" | "focus" | "commitment" | "recommendation" | "explanation">, actor: string) { const now = new Date().toISOString(); const item: OperatingPrinciple = { id: `principle_${crypto.randomUUID()}`, ...input, status: "Review required", confidence: 0, source_id: "manual_principle_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; principles = [item, ...principles]; audit("operating_principle.created", item.id, actor); return item; }
export function updatePrinciple(id: string, input: Partial<Pick<OperatingPrinciple, "principle" | "commitment" | "recommendation" | "explanation" | "status">>, actor: string) { const current = getPrinciple(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; principles = principles.map((item) => item.id === id ? updated : item); audit("operating_principle.updated", id, actor); return updated; }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function principleAuditEventCount() { return audits.length; }
