import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type PanGstinVerification = { id: string; business_id: string; application_id: string; verification_type: "PAN" | "GSTIN"; masked_reference: string; verification_status: "Verified" | "Needs review"; consent_status: "Recorded" | "Pending"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; missing_data: string[]; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let verifications: PanGstinVerification[] = [{ id: "pan_demo_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", verification_type: "PAN", masked_reference: "AA•••1234•", verification_status: "Verified", consent_status: "Recorded", source_id: "synthetic_pan_2026_07", source_observed_at: "2026-07-11T10:18:00.000Z", freshness: "Current", completeness: 100, explanation: "The masked PAN reference is consistent with the synthetic business identity record. No raw PAN is displayed or returned.", missing_data: [], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-11T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" }, { id: "gstin_demo_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", verification_type: "GSTIN", masked_reference: "27AA•••1234•1Z•", verification_status: "Needs review", consent_status: "Recorded", source_id: "synthetic_gstin_2026_05", source_observed_at: "2026-05-31T18:30:00.000Z", freshness: "Stale", completeness: 75, explanation: "The synthetic GSTIN relationship is present, but the latest filing confirmation must be refreshed before it is used for an assisted review.", missing_data: ["Latest GST filing confirmation"], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listPanGstinVerifications() { return verifications; }
export function getPanGstinVerification(id: string) { return verifications.find((verification) => verification.id === id); }
export function createPanGstinVerification(input: Pick<PanGstinVerification, "business_id" | "application_id" | "verification_type" | "masked_reference">, actor: string) { const now = new Date().toISOString(); const verification: PanGstinVerification = { id: `tax_${crypto.randomUUID()}`, ...input, verification_status: "Needs review", consent_status: "Pending", source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Awaiting consent and verification evidence from the approved adapter.", missing_data: ["Consent evidence", "Verification response"], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; verifications = [verification, ...verifications]; writeAudit("pan_gstin_verification.created", verification.id, actor); return verification; }
export function updatePanGstinVerification(id: string, input: Partial<Pick<PanGstinVerification, "consent_status">>, actor: string) { const current = getPanGstinVerification(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; verifications = verifications.map((verification) => verification.id === id ? updated : verification); writeAudit("pan_gstin_verification.updated", id, actor); return updated; }
export function panGstinVerificationAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
