import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };

export type PromoterProfile = { id: string; business_id: string; application_id: string; display_name: string; role: string; ownership_band: string; verification_status: "Verified" | "Needs review"; consent_status: "Recorded" | "Pending"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; missing_data: string[]; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let promoters: PromoterProfile[] = [{ id: "promoter_demo_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", display_name: "Anita Kulkarni", role: "Managing director", ownership_band: "Majority promoter", verification_status: "Verified", consent_status: "Recorded", source_id: "synthetic_kyb_2026_07", source_observed_at: "2026-07-11T10:15:00.000Z", freshness: "Current", completeness: 100, explanation: "Identity and authorised-signatory relationship are verified against synthetic KYB evidence. No raw identifier is exposed.", missing_data: [], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-11T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" }, { id: "promoter_demo_002", business_id: "business_demo_saraswati", application_id: "app_demo_001", display_name: "Rohan Kulkarni", role: "Director", ownership_band: "Minority promoter", verification_status: "Needs review", consent_status: "Recorded", source_id: "synthetic_kyb_2026_05", source_observed_at: "2026-05-31T18:30:00.000Z", freshness: "Stale", completeness: 72, explanation: "The director relationship is present, but refreshed identity evidence and the current address confirmation are pending review.", missing_data: ["Current address confirmation", "Refreshed identity evidence"], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listPromoterProfiles() { return promoters; }
export function getPromoterProfile(id: string) { return promoters.find((promoter) => promoter.id === id); }
export function createPromoterProfile(input: Pick<PromoterProfile, "business_id" | "application_id" | "display_name" | "role">, actor: string) { const now = new Date().toISOString(); const promoter: PromoterProfile = { id: `promoter_${crypto.randomUUID()}`, ...input, ownership_band: "Not provided", verification_status: "Needs review", consent_status: "Pending", source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Awaiting consent and supporting onboarding evidence.", missing_data: ["Consent evidence", "Identity verification"], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; promoters = [promoter, ...promoters]; writeAudit("promoter_profile.created", promoter.id, actor); return promoter; }
export function updatePromoterProfile(id: string, input: Partial<Pick<PromoterProfile, "role" | "ownership_band" | "consent_status">>, actor: string) { const current = getPromoterProfile(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; promoters = promoters.map((promoter) => promoter.id === id ? updated : promoter); writeAudit("promoter_profile.updated", id, actor); return updated; }
export function promoterProfileAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
