import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type SigninConfiguration = { id: string; provider: string; status: "Active" | "Review required"; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let configurations: SigninConfiguration[] = [{ id: "signin_demo_001", provider: "Synthetic demo session", status: "Active", explanation: "Demo sign-in validates the entered work email locally and opens a role-aware synthetic workspace. No production credential is stored or transmitted.", source_id: "signin_demo_config_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 100, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }]; const audits: Array<Record<string, string>> = [];
export function listSigninConfigurations() { return configurations; } export function getSigninConfiguration(id: string) { return configurations.find((item) => item.id === id); }
export function createSigninConfiguration(input: Pick<SigninConfiguration, "provider" | "explanation">, actor: string) { const now = new Date().toISOString(); const item: SigninConfiguration = { id: `signin_${crypto.randomUUID()}`, ...input, status: "Review required", source_id: "manual_signin_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; configurations = [item, ...configurations]; audit("signin_flow.created", item.id, actor); return item; }
export function updateSigninConfiguration(id: string, input: Partial<Pick<SigninConfiguration, "provider" | "explanation" | "status">>, actor: string) { const current = getSigninConfiguration(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; configurations = configurations.map((item) => item.id === id ? updated : item); audit("signin_flow.updated", id, actor); return updated; }
export function recordSignin(email: string) { audit("signin_flow.session_started", "signin_demo_001", email.replace(/(.{2}).+(@.*)/, "$1***$2")); }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function signinAuditEventCount() { return audits.length; }
