import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type Storyline = { id: string; chapter: string; audience: "MSME owner" | "Bank analyst" | "Risk & compliance"; narrative: string; status: "Ready" | "Needs review"; confidence: number; recommendation: string; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let storylines: Storyline[] = [
  { id: "story_owner_001", chapter: "A clearer path to credit readiness", audience: "MSME owner", narrative: "A new-to-credit MSME shares verified business details and permitted alternate evidence in manageable steps.", status: "Ready", confidence: 91, recommendation: "Lead with the borrower’s next action: verify the business and add evidence when ready.", explanation: "Copy is supportive and action-oriented; no credit outcome or model internals are disclosed.", source_id: "storyline_owner_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 100, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "story_analyst_001", chapter: "Evidence becomes an assisted review", audience: "Bank analyst", narrative: "A consistent Financial Health Card evidence pack turns alternate data into an explainable analyst recommendation.", status: "Ready", confidence: 88, recommendation: "Call out confidence, freshness, and incomplete data before presenting the assisted review outcome.", explanation: "The narrative demonstrates structured evidence and auditable recommendations, not autonomous approval.", source_id: "storyline_analyst_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 96, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "story_risk_001", chapter: "Earlier signals remain governable", audience: "Risk & compliance", narrative: "Synthetic stress signals provide explainable decision support under immutable audit controls.", status: "Needs review", confidence: 72, recommendation: "Describe the signal as synthetic decision support and refresh the governance policy snapshot before presenting.", explanation: "Live connector use, autonomous approval, and production model validation claims are explicitly out of scope.", source_id: "storyline_risk_v1", source_observed_at: "2026-05-17T08:00:00.000Z", freshness: "Stale", completeness: 69, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
]; const audits: Array<Record<string, string>> = [];
export function listStorylines() { return storylines; } export function getStoryline(id: string) { return storylines.find((storyline) => storyline.id === id); }
export function createStoryline(input: Pick<Storyline, "chapter" | "audience" | "narrative" | "recommendation" | "explanation">, actor: string) { const now = new Date().toISOString(); const storyline: Storyline = { id: `story_${crypto.randomUUID()}`, ...input, status: "Needs review", confidence: 0, source_id: "manual_storyline_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; storylines = [storyline, ...storylines]; audit("submission_storyline.created", storyline.id, actor); return storyline; }
export function updateStoryline(id: string, input: Partial<Pick<Storyline, "chapter" | "narrative" | "recommendation" | "explanation" | "status">>, actor: string) { const current = getStoryline(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; storylines = storylines.map((storyline) => storyline.id === id ? updated : storyline); audit("submission_storyline.updated", id, actor); return updated; }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function storylineAuditEventCount() { return audits.length; }
