import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type UdyamVerification = { id: string; business_id: string; application_id: string; registration_reference: string; enterprise_category: string; verification_status: "Verified" | "Needs review"; consent_status: "Recorded" | "Pending"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; missing_data: string[]; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let verifications: UdyamVerification[] = [{ id: "udyam_demo_001", business_id: "business_demo_saraswati", application_id: "app_demo_001", registration_reference: "UDYAM-MH-26-••••8412", enterprise_category: "Small enterprise", verification_status: "Verified", consent_status: "Recorded", source_id: "synthetic_udyam_2026_07", source_observed_at: "2026-07-11T10:20:00.000Z", freshness: "Current", completeness: 100, explanation: "The masked Udyam registration reference, business identity, and enterprise category match the synthetic KYB onboarding record.", missing_data: [], created_at: "2026-07-11T10:30:00.000Z", updated_at: "2026-07-11T10:30:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const auditEvents: Array<Record<string, string>> = [];
export function listUdyamVerifications() { return verifications; }
export function getUdyamVerification(id: string) { return verifications.find((verification) => verification.id === id); }
export function createUdyamVerification(input: Pick<UdyamVerification, "business_id" | "application_id" | "registration_reference" | "enterprise_category">, actor: string) { const now = new Date().toISOString(); const verification: UdyamVerification = { id: `udyam_${crypto.randomUUID()}`, ...input, verification_status: "Needs review", consent_status: "Pending", source_id: "manual_onboarding", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Awaiting consent and verification evidence from the approved adapter.", missing_data: ["Consent evidence", "Verification response"], created_at: now, updated_at: now, created_by: actor, updated_by: actor }; verifications = [verification, ...verifications]; writeAudit("udyam_verification.created", verification.id, actor); return verification; }
export function updateUdyamVerification(id: string, input: Partial<Pick<UdyamVerification, "enterprise_category" | "consent_status">>, actor: string) { const current = getUdyamVerification(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; verifications = verifications.map((verification) => verification.id === id ? updated : verification); writeAudit("udyam_verification.updated", id, actor); return updated; }
export function udyamVerificationAuditCount() { return auditEvents.length; }
function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
