import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type AdapterStatus = "Connected" | "Needs consent" | "Sync failed";
export type UliOcenAdapter = { id: string; business_name: string; masked_request_id: string; purpose: string; status: AdapterStatus; consent_status: "Recorded" | "Missing"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; last_sync_at?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type AdapterSyncJob = { id: string; adapter_id: string; status: "Completed" | "Needs review" | "Failed"; completed_at: string; source_id: string; summary: string };
export type AdapterSnapshot = { id: string; adapter_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; availability_summary: string; explanation: string; immutable: true };
let adapters: UliOcenAdapter[] = [{ id: "uli_ocen_demo_001", business_name: "Saraswati Precision Works", masked_request_id: "ULI-OCEN-••••-5641", purpose: "Assisted credit-offer discovery", status: "Connected", consent_status: "Recorded", source_id: "synthetic_uli_ocen_adapter_2026_07", source_observed_at: "2026-07-13T10:15:00.000Z", freshness: "Current", completeness: 84, explanation: "The adapter exposes a synthetic, purpose-limited availability summary. It is not a credit offer, approval, or recommendation.", last_sync_at: "2026-07-13T10:10:00.000Z", created_at: "2026-06-20T09:30:00.000Z", updated_at: "2026-07-13T10:15:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }, { id: "uli_ocen_demo_002", business_name: "Saraswati Precision Works", masked_request_id: "ULI-OCEN-••••-5641", purpose: "Lender-program eligibility exploration", status: "Needs consent", consent_status: "Missing", source_id: "synthetic_uli_ocen_adapter_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 46, explanation: "A separate purpose-limited consent is required before synthetic availability evidence may support this exploration.", created_at: "2026-06-30T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const syncJobs: AdapterSyncJob[] = [{ id: "uli_ocen_sync_demo_001", adapter_id: "uli_ocen_demo_001", status: "Completed", completed_at: "2026-07-13T10:10:00.000Z", source_id: "synthetic_uli_ocen_summary_2026_07", summary: "Latest synthetic availability summary received." }]; const snapshots: AdapterSnapshot[] = [{ id: "uli_ocen_snapshot_demo_001", adapter_id: "uli_ocen_demo_001", source_id: "synthetic_uli_ocen_summary_2026_07", observed_at: "2026-07-13T10:10:00.000Z", freshness: "Current", completeness: 84, availability_summary: "Synthetic availability signals are present for an assisted discovery workflow; no lender decision or offer is generated.", explanation: "The adapter supports future sandbox integration while retaining only a structured, redacted snapshot.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getUliOcenAdapters() { return { adapters, sync_jobs: syncJobs, source_snapshots: snapshots }; } export function getUliOcenAdapter(id: string) { return adapters.find((adapter) => adapter.id === id); }
export function createUliOcenAdapter(input: Pick<UliOcenAdapter, "business_name" | "purpose" | "masked_request_id">, actor: string) { const now = new Date().toISOString(); const adapter: UliOcenAdapter = { id: `uli_ocen_${crypto.randomUUID()}`, ...input, status: "Needs consent", consent_status: "Missing", source_id: "synthetic_uli_ocen_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Record purpose-limited consent to retrieve a synthetic ULI/OCEN availability summary. No application or lender decision is created.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; adapters = [adapter, ...adapters]; writeAudit("uli_ocen_adapter.created", adapter.id, actor); return adapter; }
export function updateUliOcenAdapter(id: string, status: AdapterStatus, actor: string) { const current = getUliOcenAdapter(id); if (!current) return undefined; const now = new Date().toISOString(); const connected = status === "Connected"; const updated = { ...current, status, consent_status: connected ? "Recorded" as const : current.consent_status, freshness: status === "Sync failed" ? "Stale" as const : current.freshness, last_sync_at: connected ? now : current.last_sync_at, updated_at: now, updated_by: actor }; adapters = adapters.map((adapter) => adapter.id === id ? updated : adapter); writeAudit("uli_ocen_adapter.updated", id, actor); return updated; }
export function uliOcenAdapterAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
