import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type UpiStatus = "Connected" | "Needs consent" | "Sync failed";
export type UpiSummaryConnector = { id: string; business_name: string; masked_vpa: string; purpose: string; status: UpiStatus; consent_status: "Recorded" | "Missing"; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; explanation: string; last_sync_at?: string; created_at: string; updated_at: string; created_by: string; updated_by: string };
export type UpiSyncJob = { id: string; connector_id: string; status: "Completed" | "Needs review" | "Failed"; completed_at: string; source_id: string; summary: string };
export type UpiSourceSnapshot = { id: string; connector_id: string; source_id: string; observed_at: string; freshness: "Current" | "Stale"; completeness: number; collection_summary: string; trend_summary: string; immutable: true };
let connectors: UpiSummaryConnector[] = [{ id: "upi_connector_demo_001", business_name: "Saraswati Precision Works", masked_vpa: "saraswati.•••@bank", purpose: "Financial health collections review", status: "Connected", consent_status: "Recorded", source_id: "synthetic_upi_connector_2026_07", source_observed_at: "2026-07-13T09:15:00.000Z", freshness: "Current", completeness: 91, explanation: "The connector provides aggregated UPI collections and trend summaries for assisted review. Individual payer and transaction details are not displayed.", last_sync_at: "2026-07-13T09:10:00.000Z", created_at: "2026-06-20T09:30:00.000Z", updated_at: "2026-07-13T09:15:00.000Z", created_by: "demo.borrower", updated_by: "system.seed" }, { id: "upi_connector_demo_002", business_name: "Saraswati Precision Works", masked_vpa: "saraswati.•••@bank", purpose: "Default-risk collection monitoring", status: "Needs consent", consent_status: "Missing", source_id: "synthetic_upi_connector_2026_06", source_observed_at: "2026-06-30T10:00:00.000Z", freshness: "Stale", completeness: 48, explanation: "A separate purpose-limited consent is required before UPI collection summaries may support monitoring evidence.", created_at: "2026-06-30T10:00:00.000Z", updated_at: "2026-06-30T10:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" }];
const syncJobs: UpiSyncJob[] = [{ id: "upi_sync_demo_001", connector_id: "upi_connector_demo_001", status: "Completed", completed_at: "2026-07-13T09:10:00.000Z", source_id: "synthetic_upi_summary_2026_07", summary: "Latest aggregated collections summary received." }]; const snapshots: UpiSourceSnapshot[] = [{ id: "upi_snapshot_demo_001", connector_id: "upi_connector_demo_001", source_id: "synthetic_upi_summary_2026_07", observed_at: "2026-07-13T09:10:00.000Z", freshness: "Current", completeness: 91, collection_summary: "₹12.75 lakh in aggregated incoming collections over the latest available 90-day summary.", trend_summary: "Collections frequency remained stable compared with the preceding summary period.", immutable: true }]; const auditEvents: Array<Record<string, string>> = [];
export function getUpiSummaryConnectors() { return { connectors, sync_jobs: syncJobs, source_snapshots: snapshots }; } export function getUpiSummaryConnector(id: string) { return connectors.find((connector) => connector.id === id); }
export function createUpiSummaryConnector(input: Pick<UpiSummaryConnector, "business_name" | "purpose" | "masked_vpa">, actor: string) { const now = new Date().toISOString(); const connector: UpiSummaryConnector = { id: `upi_connector_${crypto.randomUUID()}`, ...input, status: "Needs consent", consent_status: "Missing", source_id: "synthetic_upi_connector_request", source_observed_at: now, freshness: "Current", completeness: 0, explanation: "Record purpose-limited consent to retrieve a synthetic UPI summary. Individual transaction payloads are not stored or displayed.", created_at: now, updated_at: now, created_by: actor, updated_by: actor }; connectors = [connector, ...connectors]; writeAudit("upi_summary_connector.created", connector.id, actor); return connector; }
export function updateUpiSummaryConnector(id: string, status: UpiStatus, actor: string) { const current = getUpiSummaryConnector(id); if (!current) return undefined; const now = new Date().toISOString(); const connected = status === "Connected"; const updated = { ...current, status, consent_status: connected ? "Recorded" as const : current.consent_status, freshness: status === "Sync failed" ? "Stale" as const : current.freshness, last_sync_at: connected ? now : current.last_sync_at, updated_at: now, updated_by: actor }; connectors = connectors.map((connector) => connector.id === id ? updated : connector); writeAudit("upi_summary_connector.updated", id, actor); return updated; }
export function upiSummaryConnectorAuditCount() { return auditEvents.length; } function writeAudit(event_type: string, entity_id: string, actor_id: string) { auditEvents.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); }
