import { apiError, getActor, isAllowedRole, traceId } from "./problem-statement-fit.ts";
export { apiError, getActor, isAllowedRole, traceId };
export type RoleMap = { id: string; role: "Borrower" | "Bank analyst" | "Risk & compliance" | "Administrator"; access: string; purpose: string; boundary: string; status: "Active" | "Review required"; confidence: number; explanation: string; source_id: string; source_observed_at: string; freshness: "Current" | "Stale"; completeness: number; created_at: string; updated_at: string; created_by: string; updated_by: string; };
let roles: RoleMap[] = [
  { id: "role_borrower_001", role: "Borrower", access: "Own organization profile and approved explanations", purpose: "Help an MSME demonstrate readiness through permitted evidence.", boundary: "No model internals, raw sensitive payloads, or credit decision controls.", status: "Active", confidence: 94, explanation: "Borrower access is purpose-limited and the copy remains supportive and action-oriented.", source_id: "role_policy_borrower_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 100, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "role_analyst_001", role: "Bank analyst", access: "Evidence packs, confidence, freshness, and assisted recommendations", purpose: "Complete consistent reviews faster with explainable evidence.", boundary: "Cannot autonomously approve credit or access unconsented data.", status: "Active", confidence: 91, explanation: "Analyst work is supported by visible confidence, stale-data, and missing-data indicators.", source_id: "role_policy_analyst_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 98, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "role_risk_001", role: "Risk & compliance", access: "Audit evidence, configuration review, and governance outputs", purpose: "Review decision-support controls and exceptions.", boundary: "Does not expose raw alternate-data payloads or authorize live data use.", status: "Review required", confidence: 75, explanation: "The synthetic governance policy snapshot requires refreshing before production reliance.", source_id: "role_policy_risk_v1", source_observed_at: "2026-05-18T08:00:00.000Z", freshness: "Stale", completeness: 74, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
  { id: "role_admin_001", role: "Administrator", access: "Configuration and role-management controls", purpose: "Maintain secure platform setup with traceable changes.", boundary: "Must preserve immutable audit records and least-privilege access.", status: "Active", confidence: 88, explanation: "Role configuration changes are audit-event producing operations.", source_id: "role_policy_admin_v1", source_observed_at: "2026-07-12T08:00:00.000Z", freshness: "Current", completeness: 96, created_at: "2026-07-12T08:00:00.000Z", updated_at: "2026-07-12T08:00:00.000Z", created_by: "system.seed", updated_by: "system.seed" },
]; const audits: Array<Record<string, string>> = [];
export function listRoleMaps() { return roles; } export function getRoleMap(id: string) { return roles.find((role) => role.id === id); }
export function createRoleMap(input: Pick<RoleMap, "role" | "access" | "purpose" | "boundary" | "explanation">, actor: string) { const now = new Date().toISOString(); const role: RoleMap = { id: `role_${crypto.randomUUID()}`, ...input, status: "Review required", confidence: 0, source_id: "manual_role_entry", source_observed_at: now, freshness: "Current", completeness: 0, created_at: now, updated_at: now, created_by: actor, updated_by: actor }; roles = [role, ...roles]; audit("user_role_map.created", role.id, actor); return role; }
export function updateRoleMap(id: string, input: Partial<Pick<RoleMap, "access" | "purpose" | "boundary" | "explanation" | "status">>, actor: string) { const current = getRoleMap(id); if (!current) return undefined; const updated = { ...current, ...input, updated_at: new Date().toISOString(), updated_by: actor }; roles = roles.map((role) => role.id === id ? updated : role); audit("user_role_map.updated", id, actor); return updated; }
function audit(event_type: string, entity_id: string, actor_id: string) { audits.push({ id: `audit_${crypto.randomUUID()}`, event_type, entity_id, actor_id, occurred_at: new Date().toISOString() }); } export function roleAuditEventCount() { return audits.length; }
