export class AccountAggregatorError extends Error { code: string; status: number; retryable: boolean; constructor(code: string, message: string, status = 502, retryable = false) { super(message); this.code = code; this.status = status; this.retryable = retryable; } }
export class SetuAuthenticationError extends AccountAggregatorError { constructor() { super("SETU_AUTHENTICATION_ERROR", "The financial-data provider could not authenticate the request.", 502); } }
export class SetuValidationError extends AccountAggregatorError { constructor(message = "The financial-data request is invalid.") { super("SETU_VALIDATION_ERROR", message, 400); } }
export class SetuConsentNotActiveError extends AccountAggregatorError { constructor() { super("SETU_CONSENT_NOT_ACTIVE", "Financial-data consent is not active.", 409); } }
export class SetuRateLimitError extends AccountAggregatorError { constructor() { super("SETU_RATE_LIMITED", "The provider is busy. Please try again shortly.", 429, true); } }
export class SetuUpstreamUnavailableError extends AccountAggregatorError { constructor() { super("SETU_UPSTREAM_UNAVAILABLE", "The provider is temporarily unavailable.", 503, true); } }
export class SetuConfigurationError extends AccountAggregatorError { constructor(message = "Setu sandbox configuration is incomplete.") { super("SETU_CONFIGURATION_ERROR", message, 503); } }
export class SetuWebhookVerificationError extends AccountAggregatorError { constructor() { super("SETU_WEBHOOK_VERIFICATION_ERROR", "Webhook verification failed.", 401); } }
export function problem(error: unknown, correlationId: string) { const known = error instanceof AccountAggregatorError ? error : new AccountAggregatorError("INTERNAL_ERROR", "The request could not be completed.", 500); return Response.json({ type: `https://msme-arogya360/errors/${known.code.toLowerCase()}`, title: known.message, status: known.status, code: known.code, correlation_id: correlationId }, { status: known.status }); }
