export type ConsentStatus = "PENDING" | "ACTIVE" | "REJECTED" | "REVOKED" | "PAUSED" | "EXPIRED";
export type SessionStatus = "NOT_CREATED" | "PENDING" | "PARTIAL" | "COMPLETED" | "FAILED" | "EXPIRED";
export type CreateConsentInput = { userId: string; organisationId: string; mobileNumber: string; from: string; to: string; fetchType: "ONETIME" | "PERIODIC"; correlationId: string };
export type CreateConsentResult = { id: string; url: string; status: ConsentStatus; traceId?: string };
export type ConsentResult = CreateConsentResult & { rejectionCode?: string };
export type CreateDataSessionInput = { consentId: string; dataRange: { from: string; to: string }; format: "json" };
export type DataSessionResult = { id: string; consentId: string; status: SessionStatus; traceId?: string; dataRange: { from: string; to: string } };
export type FinancialDataResult = { sessionId: string; status: SessionStatus; accounts: unknown[]; traceId?: string };
export interface AccountAggregatorProvider { createConsent(input: CreateConsentInput): Promise<CreateConsentResult>; getConsent(consentId: string): Promise<ConsentResult>; revokeConsent(consentId: string): Promise<ConsentResult>; createDataSession(input: CreateDataSessionInput): Promise<DataSessionResult>; fetchFinancialData(sessionId: string): Promise<FinancialDataResult>; }
export type NormalizedFinancialAccount = { provider: "SETU"; fipId: string; linkedAccountReference: string; maskedAccountNumber: string; accountType: string; fiType: string; currency: string; status: string; currentBalance?: string; balanceAsOf?: Date };
export type NormalizedFinancialTransaction = { externalTransactionId?: string; linkedAccountReference: string; type: "CREDIT" | "DEBIT" | "OTHER"; mode?: string; amount: string; currency: string; balanceAfterTransaction?: string; transactionTimestamp: Date; valueDate?: Date; deduplicationHash: string };
export type MetricValue = { value: number | null; status: "AVAILABLE" | "INSUFFICIENT_DATA" | "NOT_APPLICABLE"; confidence: number; sourcePeriod: { from: string; to: string }; calculationVersion: string };
export type DefaultRiskFeatureVector = { averageMonthlyInflow: number; averageMonthlyOutflow: number; netCashFlowMargin: number; cashFlowVolatility: number; inflowTrend: number; averageBalance: number; lowBalanceDayRatio: number; negativeCashFlowMonthRatio: number; liquidityBufferDays: number; fixedObligationToInflowRatio: number; debtServiceCoverageProxy: number; revenueConcentration: number; recurringRevenueRatio: number; failedPaymentIndicatorCount: number; transactionHistoryMonths: number; dataCompleteness: number };
export type FinancialMetrics = { sufficient: boolean; partial: boolean; dataCompleteness: number; totalInflows: MetricValue; totalOutflows: MetricValue; netCashFlow: MetricValue; averageMonthlyInflow: MetricValue; averageMonthlyOutflow: MetricValue; transactionHistoryMonths: number; transactionCount: number; accountCount: number };
export type FinancialSummary = { organisationId: string; connectedAccounts: number; dataCompleteness: number; sufficient: boolean; metrics: FinancialMetrics; features: DefaultRiskFeatureVector | null; featureSchemaVersion: string | null; generatedAt: string };
