import { createHash, createVerify, timingSafeEqual } from "node:crypto"; import { z } from "zod"; import { aaStore } from "./store.ts"; import { SetuWebhookVerificationError, SetuValidationError } from "./errors.ts";
export type WebhookVerification = { secret?: string | null; jwsSignature?: string | null; rawBody?: string };
const consentSchema = z.object({ notificationId: z.string().optional(), consentId: z.string(), timestamp: z.string(), type: z.literal("CONSENT_STATUS_UPDATE"), success: z.boolean(), data: z.object({ status: z.enum(["ACTIVE", "REJECTED", "REVOKED", "PAUSED", "EXPIRED"]), detail: z.unknown().optional() }).nullable(), error: z.object({ code: z.string(), message: z.string() }).nullable().optional() }); const sessionSchema = z.object({ notificationId: z.string().optional(), dataSessionId: z.string(), consentId: z.string(), timestamp: z.string(), type: z.literal("SESSION_STATUS_UPDATE"), success: z.boolean(), data: z.object({ status: z.enum(["PENDING", "PARTIAL", "COMPLETED", "FAILED", "EXPIRED"]), fips: z.array(z.unknown()).optional(), format: z.string().optional() }), error: z.unknown().nullable().optional() });
export function verifyWebhookSecret(value: string | null) { const secret = process.env.SETU_WEBHOOK_VERIFICATION_SECRET; if (!secret) return process.env.SETU_MODE === "demo"; if (!value) return false; const left = Buffer.from(value); const right = Buffer.from(secret); return left.length === right.length && timingSafeEqual(left, right); }
// Verifies Setu's detached JWS (`x-jws-signature`: `<protected>..<signature>`) over the raw request body using an
// RS256 public key. Confirm the exact alg/key format against your Setu notification-signing setup before prod.
export function verifyDetachedJws(jwsSignature: string, rawBody: string, publicKeyPem: string) { try { const [protectedHeader, , signature] = jwsSignature.split("."); if (!protectedHeader || !signature) return false; const signingInput = `${protectedHeader}.${Buffer.from(rawBody).toString("base64url")}`; return createVerify("RSA-SHA256").update(signingInput).verify(publicKeyPem, Buffer.from(signature, "base64url")); } catch { return false; } }
export function isWebhookVerified(verification: WebhookVerification | null) { const publicKey = process.env.SETU_WEBHOOK_JWS_PUBLIC_KEY; if (publicKey && verification?.jwsSignature && verification?.rawBody) return verifyDetachedJws(verification.jwsSignature, verification.rawBody, publicKey); return verifyWebhookSecret(verification?.secret ?? null); }
export function processConsentWebhook(raw: unknown, verification: WebhookVerification | null) { if (!isWebhookVerified(verification)) throw new SetuWebhookVerificationError(); const event = consentSchema.parse(raw); const eventId = event.notificationId ?? payloadHash(JSON.stringify(event)); if (!aaStore.claimWebhook(eventId)) return { duplicate: true }; const consent = aaStore.getConsent(event.consentId); if (!consent) throw new SetuValidationError("Unknown consent notification."); const status = event.data?.status ?? (event.error?.code === "UserCancelled" ? "PENDING" : "REJECTED"); aaStore.updateConsent(consent.id, { status }); return { duplicate: false, status }; }
export function processSessionWebhook(raw: unknown, verification: WebhookVerification | null) { if (!isWebhookVerified(verification)) throw new SetuWebhookVerificationError(); const event = sessionSchema.parse(raw); const eventId = event.notificationId ?? payloadHash(JSON.stringify(event)); if (!aaStore.claimWebhook(eventId)) return { duplicate: true }; const session = aaStore.getSession(event.dataSessionId); if (!session) throw new SetuValidationError("Unknown session notification."); aaStore.updateSession(session.id, { status: event.data.status }); return { duplicate: false, status: event.data.status }; }
export function payloadHash(raw: string) { return createHash("sha256").update(raw).digest("hex"); }
