"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox, Input, Label } from "@/components/ui/form";
import { Separator } from "@/components/ui/separator";
export default function SignUpPage() { const router = useRouter(); const [email, setEmail] = useState(""); const [businessName, setBusinessName] = useState(""); const [terms, setTerms] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!terms) return setMessage("Please accept the prototype terms and privacy notice."); setLoading(true); setMessage(""); try { const response = await fetch("/api/v1/signup-invite-flow", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, business_name: businessName }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || "Signup is unavailable."); router.push(payload.data.redirect); } catch (error) { setMessage(error instanceof Error ? error.message : "Signup is unavailable."); setLoading(false); } }; return <main className="auth-new"><Card><CardHeader><p className="auth-brand">MSME Arogya360</p><CardTitle>Start your readiness journey</CardTitle><CardDescription>We’ll guide you through the evidence you can choose to share.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="auth-form-new"><div><Label htmlFor="business-name">Business name</Label><Input id="business-name" value={businessName} onChange={(event) => setBusinessName(event.target.value)} placeholder="Your MSME name" minLength={2} required /></div><div><Label htmlFor="signup-email">Business email</Label><Input id="signup-email" value={email} onChange={(event) => setEmail(event.target.value)} type="email" placeholder="owner@business.in" required /></div><Label className="check-label"><Checkbox checked={terms} onChange={(event) => setTerms(event.target.checked)} />I agree to the prototype terms and privacy notice.</Label>{message && <Alert className="error-alert"><AlertTitle>Workspace creation unavailable</AlertTitle><AlertDescription>{message}</AlertDescription></Alert>}<Button type="submit" disabled={loading}>{loading ? "Creating invite…" : "Create demo workspace"}</Button></form><Separator /><p className="auth-note">Synthetic demo invitation only. No real invite is sent.</p><div className="auth-links"><Link href="/signin">Already have an account? Sign in</Link></div></CardContent></Card></main>; }
