"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Features = { netCashFlowMargin: number; liquidityBufferDays: number; averageMonthlyInflow: number; transactionHistoryMonths: number } & Record<string, number>;
type Summary = { connectedAccounts: number; dataCompleteness: number; sufficient: boolean; features: Features | null; featureSchemaVersion: string | null; metrics: { transactionHistoryMonths: number; transactionCount: number }; generatedAt: string };
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
export default function DefaultRiskSummary() {
  const [summary, setSummary] = useState<Summary | null | undefined>(undefined);
  const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/integrations/setu/financial-summary").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.title); setSummary(body.data as Summary | null); }).catch((value) => setError(value instanceof Error ? value.message : "Default risk is unavailable.")); }, []);
  if (error) return <main className="state-panel error-state"><strong>Default risk unavailable</strong><span>{error}</span></main>;
  if (summary === undefined) return <main className="state-panel"><span className="spinner" aria-label="Loading" /><strong>Loading default-risk estimate…</strong></main>;
  const features = summary?.features ?? null;
  return <main className="workspace"><section className="hero"><div><p className="eyebrow">12-month analytical estimate</p><h1>Default risk</h1><p>An explainable estimate based on available financial information—not a lending decision or certainty.</p></div><div className="hero-status">{features ? <><span className="live-dot" />Features ready</> : "Insufficient data"}<small>{features ? `${summary?.featureSchemaVersion}` : "Model inference has not run"}</small></div></section><section className="metrics"><article className="metric"><span>Estimated probability</span><strong>—</strong><small>No production or mock prediction substituted</small></article><article className="metric"><span>Risk band</span><strong>—</strong><small>Versioned thresholds apply after inference</small></article><article className="metric"><span>Data quality</span><strong>{summary ? `${summary.dataCompleteness}%` : "0%"}</strong><small>Derived features only are sent to the model</small></article></section>{features && <section className="metrics"><article className="metric"><span>Net cash-flow margin</span><strong>{pct(features.netCashFlowMargin)}</strong><small>Net flow ÷ inflow</small></article><article className="metric"><span>Liquidity buffer</span><strong>{Math.round(features.liquidityBufferDays)} days</strong><small>Runway at current outflow</small></article><article className="metric"><span>History</span><strong>{features.transactionHistoryMonths} mo</strong><small>{summary?.metrics.transactionCount} transactions</small></article></section>}<section className="info-banner"><strong>Rules-based financial metrics remain available if the ML service is unavailable.</strong> Raw bank statements are not sent to the model by default.</section>{!features && <Link className="ui-button" href="/app/data-connections">Review data connection</Link>}</main>;
}
