"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type MetricValue = { value: number | null; status: string; confidence: number };
type Summary = { connectedAccounts: number; dataCompleteness: number; sufficient: boolean; metrics: { totalInflows: MetricValue; totalOutflows: MetricValue; netCashFlow: MetricValue; averageMonthlyInflow: MetricValue; averageMonthlyOutflow: MetricValue; transactionHistoryMonths: number; transactionCount: number; accountCount: number }; generatedAt: string };
const inr = (value: number | null) => (value == null ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value));
export default function FinancialHealthSummary() {
  const [summary, setSummary] = useState<Summary | null | undefined>(undefined);
  const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/integrations/setu/financial-summary").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.title); setSummary(body.data as Summary | null); }).catch((value) => setError(value instanceof Error ? value.message : "Financial health is unavailable.")); }, []);
  if (error) return <main className="state-panel error-state"><strong>Financial health unavailable</strong><span>{error}</span></main>;
  if (summary === undefined) return <main className="state-panel"><span className="spinner" aria-label="Loading" /><strong>Loading financial health…</strong></main>;
  if (!summary || !summary.sufficient) return <main className="workspace"><section className="hero"><div><p className="eyebrow">Financial Health Card</p><h1>Financial health</h1><p>Cash-flow, liquidity, revenue consistency, obligations, and financial discipline derived from consented account information.</p></div><div className="hero-status">Awaiting verified data<small>Minimum 90 days, 20 transactions, and two active months</small></div></section><section className="metrics"><article className="metric"><span>Data completeness</span><strong>{summary ? `${summary.dataCompleteness}%` : "0%"}</strong><small>Partial sessions remain visibly incomplete</small></article><article className="metric"><span>Connected accounts</span><strong>{summary ? summary.connectedAccounts : 0}</strong><small>Connect accounts to begin</small></article><article className="metric"><span>Transactions</span><strong>{summary ? summary.metrics.transactionCount : 0}</strong><small>Not calculated without sufficient data</small></article></section><section className="info-banner"><strong>No synthetic score is shown.</strong> Connect Setu accounts and complete FI ingestion before metrics are calculated.</section><Link className="ui-button" href="/app/data-connections/setu">Connect bank accounts</Link></main>;
  const { metrics } = summary;
  return <main className="workspace"><section className="hero"><div><p className="eyebrow">Financial Health Card</p><h1>Financial health</h1><p>Derived from consented Account Aggregator data across {summary.connectedAccounts} account{summary.connectedAccounts === 1 ? "" : "s"} and {metrics.transactionHistoryMonths} months.</p></div><div className="hero-status"><span className="live-dot" />Verified data<small>Updated {new Date(summary.generatedAt).toLocaleString("en-IN")}</small></div></section><section className="metrics"><article className="metric"><span>Avg monthly inflow</span><strong>{inr(metrics.averageMonthlyInflow.value)}</strong><small>Credits across the consented period</small></article><article className="metric"><span>Avg monthly outflow</span><strong>{inr(metrics.averageMonthlyOutflow.value)}</strong><small>Debits across the consented period</small></article><article className="metric"><span>Net cash flow</span><strong>{inr(metrics.netCashFlow.value)}</strong><small>Inflows minus outflows</small></article><article className="metric"><span>Data completeness</span><strong>{summary.dataCompleteness}%</strong><small>{metrics.transactionCount} transactions ingested</small></article></section><section className="info-banner"><strong>Calculation version {metrics.averageMonthlyInflow.status === "AVAILABLE" ? "cashflow-v1" : "pending"}.</strong> Figures reflect consented deposit-account data only and are not a lending decision.</section></main>;
}
